export const REPORT_TYPES = [
  { key: 'center-wise', icon: 'bi-building', color: '#0d6efd', labelBn: 'কেন্দ্রভিত্তিক পারফরম্যান্স', labelEn: 'Center Performance', desc: 'প্রতি কেন্দ্রের ব্যাচ, প্রশিক্ষণার্থী, স্থাপন ও বাজেটের সারাংশ' },
  { key: 'course-wise', icon: 'bi-book', color: '#6610f2', labelBn: 'কোর্স সমাপ্তি', labelEn: 'Course Completion', desc: 'কোর্সভিত্তিক সমাপ্তি, ড্রপআউট ও ফেইল রেট' },
  { key: 'trainer-performance', icon: 'bi-person-workspace', color: '#fd7e14', labelBn: 'প্রশিক্ষক মূল্যায়ন', labelEn: 'Trainer Performance', desc: 'প্রশিক্ষকের সেশন ও প্রশিক্ষণার্থীর সংখ্যা' },
  { key: 'assessor-performance', icon: 'bi-clipboard-check', color: '#20c997', labelBn: 'মূল্যায়নকারী মূল্যায়ন', labelEn: 'Assessor Performance', desc: 'মূল্যায়নকারীর অ্যাসেসমেন্ট, পাস রেট ও গড় স্কোর' },
  { key: 'trainee-demographics', icon: 'bi-people', color: '#dc3545', labelBn: 'প্রশিক্ষণার্থী ডেমোগ্রাফিক', labelEn: 'Trainee Demographics', desc: 'বয়স ও লিঙ্গভিত্তিক প্রশিক্ষণার্থী বিশ্লেষণ' },
  { key: 'attendance-compliance', icon: 'bi-calendar-check', color: '#198754', labelBn: 'উপস্থিতি কমপ্লায়েন্স', labelEn: 'Attendance Compliance', desc: '৮০% এর নিচে উপস্থিতি সহ কেন্দ্রসমূহ' },
  { key: 'assessment', icon: 'bi-bar-chart', color: '#0dcaf0', labelBn: 'মূল্যায়ন (পাস/ফেল)', labelEn: 'Assessment Pass/Fail', desc: 'মূল্যায়নের পাস/ফেল রেট, ধরন ও গড় নম্বর' },
  { key: 'certificate', icon: 'bi-award', color: '#6f42c1', labelBn: 'সার্টিফিকেট ইস্যু', labelEn: 'Certificate Issuance', desc: 'ইস্যুকৃত সার্টিফিকেট এবং ভেরিফিকেশন সংখ্যা' },
  { key: 'job-placement', icon: 'bi-briefcase', color: '#e83e8c', labelBn: 'চাকরি স্থাপন', labelEn: 'Job Placement', desc: 'স্থাপন সংখ্যা, ধরণ ও গড় বেতন' },
  { key: 'financial-soe', icon: 'bi-cash-stack', color: '#198754', labelBn: 'ব্যয় বিবরণী (SoE)', labelEn: 'Financial SoE', desc: 'অনুমোদিত ভাউচারের ভিত্তিতে ব্যয় বিবরণী' },
  { key: 'budget-vs-actual', icon: 'bi-pie-chart', color: '#dc3545', labelBn: 'বাজেট বনাম প্রকৃত', labelEn: 'Budget vs Actual', desc: 'কেন্দ্র ও অর্থবছর ভিত্তিক বাজেট ব্যবহার' },
  { key: 'batch-completion', icon: 'bi-layers', color: '#0d6efd', labelBn: 'ব্যাচ সমাপ্তি', labelEn: 'Batch Completion', desc: 'প্রতি ব্যাচের প্রশিক্ষণার্থী, সমাপ্তি ও ড্রপআউট' },
  { key: 'application-funnel', icon: 'bi-funnel', color: '#fd7e14', labelBn: 'আবেদন ফানেল', labelEn: 'Application Funnel', desc: 'আবেদন থেকে নির্বাচন পর্যন্ত কনভার্সন রেট' },
  { key: 'revenue', icon: 'bi-coin', color: '#ffc107', labelBn: 'রেভিনিউ', labelEn: 'Revenue', desc: 'ফি সংগ্রহ ও আনুমানিক আয়' },
  { key: 'gender-diversity', icon: 'bi-gender-ambiguous', color: '#e83e8c', labelBn: 'লিঙ্গ বৈচিত্র্য', labelEn: 'Gender Diversity', desc: 'কেন্দ্র ভিত্তিক নারী অংশগ্রহণ' },
  { key: 'regional', icon: 'bi-geo-alt', color: '#20c997', labelBn: 'আঞ্চলিক (২৭ কেন্দ্র)', labelEn: 'Regional Comparison', desc: 'সব কেন্দ্রের তুলনামূলক বিশ্লেষণ' },
  { key: 'monthly-trend', icon: 'bi-graph-up', color: '#0d6efd', labelBn: 'মাসিক প্রবণতা', labelEn: 'Monthly Trend', desc: 'মাস অনুযায়ী নতুন প্রশিক্ষণার্থী ও আবেদন' },
  { key: 'audit-log', icon: 'bi-journal-text', color: '#6c757d', labelBn: 'অডিট লগ', labelEn: 'Audit Log', desc: 'সিস্টেম কার্যক্রমের বিবরণ' },
  { key: 'compliance', icon: 'bi-shield-check', color: '#198754', labelBn: 'টিওআর কমপ্লায়েন্স', labelEn: 'TOR Compliance', desc: 'টিওআর অনুযায়ী সামগ্রিক কমপ্লায়েন্স' },
];
