# Generated by Django 4.2.16 on 2026-05-07 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(editable=False, max_length=30, unique=True, verbose_name='ব্যাচ নম্বর')),
                ('custom_batch_no', models.CharField(blank=True, help_text='ঐচ্ছিক: নিজস্ব ব্যাচ নম্বর দিলে এখানে দিন', max_length=50, verbose_name='কাস্টম ব্যাচ নম্বর')),
                ('batch_name_bn', models.CharField(max_length=255, verbose_name='ব্যাচের নাম (বাংলায়)')),
                ('batch_name_en', models.CharField(max_length=255, verbose_name='ব্যাচের নাম (ইংরেজিতে)')),
                ('start_date', models.DateField(verbose_name='শুরুর তারিখ')),
                ('end_date', models.DateField(verbose_name='শেষের তারিখ')),
                ('total_seats', models.PositiveIntegerField(verbose_name='মোট আসন')),
                ('filled_seats', models.PositiveIntegerField(default=0, verbose_name='পূরণকৃত আসন')),
                ('waitlist_seats', models.PositiveIntegerField(default=0, verbose_name='অপেক্ষমাণ আসন')),
                ('status', models.CharField(choices=[('scheduled', 'নির্ধারিত'), ('running', 'চলমান'), ('completed', 'সমাপ্ত'), ('cancelled', 'বাতিল')], default='scheduled', max_length=20, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ব্যাচ',
                'verbose_name_plural': 'ব্যাচসমূহ',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='BatchWeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_no', models.PositiveIntegerField(verbose_name='টার্ম নম্বর')),
                ('term_day', models.PositiveIntegerField(verbose_name='টার্মের দিন')),
                ('session_no', models.PositiveIntegerField(verbose_name='সেশন নম্বর')),
                ('class_type', models.CharField(choices=[('theory', 'তত্ত্ব'), ('practical', 'ব্যবহারিক'), ('assessment', 'মূল্যায়ন')], max_length=20, verbose_name='ক্লাসের ধরণ')),
                ('start_date', models.DateField(verbose_name='শুরুর তারিখ')),
                ('end_date', models.DateField(verbose_name='শেষের তারিখ')),
                ('day_of_week', models.IntegerField(choices=[(6, 'শনিবার'), (0, 'রবিবার'), (1, 'সোমবার'), (2, 'মঙ্গলবার'), (3, 'বুধবার'), (4, 'বৃহস্পতিবার'), (5, 'শুক্রবার')], verbose_name='বার')),
                ('start_time', models.TimeField(verbose_name='শুরুর সময়')),
                ('end_time', models.TimeField(verbose_name='শেষের সময়')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='সময়কাল (ঘন্টা)')),
                ('training_room_bn', models.CharField(max_length=255, verbose_name='কক্ষ (বাংলায়)')),
                ('training_room_en', models.CharField(max_length=255, verbose_name='কক্ষ (ইংরেজিতে)')),
                ('topic_bn', models.CharField(max_length=500, verbose_name='বিষয় (বাংলায়)')),
                ('topic_en', models.CharField(blank=True, max_length=500, verbose_name='বিষয় (ইংরেজিতে)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associate_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associate_sessions', to='trainers.trainer', verbose_name='সহকারী প্রশিক্ষক')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_plans', to='batches.batch', verbose_name='ব্যাচ')),
                ('lead_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sessions', to='trainers.trainer', verbose_name='প্রধান প্রশিক্ষক')),
            ],
            options={
                'verbose_name': 'ব্যাচ সাপ্তাহিক পরিকল্পনা',
                'verbose_name_plural': 'ব্যাচ সাপ্তাহিক পরিকল্পনা',
                'ordering': ('batch', 'term_no', 'term_day', 'session_no'),
            },
        ),
        migrations.CreateModel(
            name='BatchEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='নথিভুক্তির তারিখ')),
                ('status', models.CharField(choices=[('active', 'সক্রিয়'), ('dropped', 'বহিষ্কৃত'), ('completed', 'সমাপ্ত')], default='active', max_length=20, verbose_name='অবস্থা')),
                ('dropped_date', models.DateField(blank=True, null=True, verbose_name='বহিষ্কারের তারিখ')),
                ('drop_reason', models.TextField(blank=True, verbose_name='বহিষ্কারের কারণ')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='batches.batch', verbose_name='ব্যাচ')),
            ],
            options={
                'verbose_name': 'ব্যাচে নথিভুক্তি',
                'verbose_name_plural': 'ব্যাচে নথিভুক্তি',
                'ordering': ('-enrollment_date',),
            },
        ),
    ]
