# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0001_initial'),
        ('circulars', '0001_initial'),
        ('trainees', '0001_initial'),
        ('courses', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchenrollment',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='trainees.trainee', verbose_name='প্রশিক্ষণার্থী'),
        ),
        migrations.AddField(
            model_name='batch',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='centers.center', verbose_name='প্রশিক্ষণ কেন্দ্র'),
        ),
        migrations.AddField(
            model_name='batch',
            name='circular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='circulars.circular', verbose_name='সার্কুলার'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course', verbose_name='কোর্স'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন'),
        ),
        migrations.AddIndex(
            model_name='batchweekplan',
            index=models.Index(fields=['batch', 'term_no'], name='batches_bat_batch_i_207528_idx'),
        ),
        migrations.AddIndex(
            model_name='batchweekplan',
            index=models.Index(fields=['lead_trainer', 'day_of_week'], name='batches_bat_lead_tr_a7d3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='batchenrollment',
            index=models.Index(fields=['batch', 'status'], name='batches_bat_batch_i_28b843_idx'),
        ),
        migrations.AddIndex(
            model_name='batchenrollment',
            index=models.Index(fields=['trainee'], name='batches_bat_trainee_a2d08c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchenrollment',
            unique_together={('trainee', 'batch')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['center', 'status'], name='batches_bat_center__28b3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['circular', 'status'], name='batches_bat_circula_30c9de_idx'),
        ),
    ]
