# Generated by Django 5.0 on 2026-06-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
        ('centers', '0005_center_center_type_center_latitude_center_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_index',
            field=models.PositiveIntegerField(blank=True, help_text='কেন্দ্রের মধ্যে ব্যাচের ক্রমিক নম্বর (১ থেকে শুরু)', null=True, verbose_name='ব্যাচ ক্রম'),
        ),
        migrations.AddField(
            model_name='batch',
            name='shift',
            field=models.CharField(blank=True, choices=[('shift_1', 'শিফট-১'), ('shift_2', 'শিফট-২')], max_length=10, null=True, verbose_name='শিফট'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_seats',
            field=models.PositiveIntegerField(default=25, verbose_name='মোট আসন'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=100, verbose_name='নাম (ইংরেজিতে)')),
                ('start_time', models.TimeField(verbose_name='শুরুর সময়')),
                ('end_time', models.TimeField(verbose_name='শেষের সময়')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='centers.center', verbose_name='কেন্দ্র')),
            ],
            options={
                'verbose_name': 'শিফট',
                'verbose_name_plural': 'শিফট',
                'ordering': ('center', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('description_bn', models.CharField(max_length=255, verbose_name='বিবরণ (বাংলায়)')),
                ('description_en', models.CharField(blank=True, max_length=255, verbose_name='বিবরণ (ইংরেজিতে)')),
                ('is_government_holiday', models.BooleanField(default=True, verbose_name='সরকারি ছুটি')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, help_text='খালি রাখলে সকল কেন্দ্রের জন্য প্রযোজ্য', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='centers.center', verbose_name='কেন্দ্র (ঐচ্ছিক)')),
            ],
            options={
                'verbose_name': 'ছুটির দিন',
                'verbose_name_plural': 'ছুটির দিন',
                'ordering': ('-date',),
                'unique_together': {('date', 'center')},
            },
        ),
    ]
