# Generated by Django 5.0 on 2026-06-13 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_batch_index_batch_shift_and_more'),
        ('centers', '0005_center_center_type_center_latitude_center_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='center',
            field=models.ForeignKey(blank=True, help_text='খালি রাখলে সকল কেন্দ্রের জন্য প্রযোজ্য (হেড অফিস)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='centers.center', verbose_name='কেন্দ্র'),
        ),
    ]
