# Generated by Django 5.0 on 2026-06-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_make_shift_center_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchweekplan',
            name='training_room_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='কক্ষ (ইংরেজিতে)'),
        ),
    ]
