# Generated by Django 5.0 on 2026-06-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_training_room_en_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('total_sessions', models.PositiveIntegerField(default=1, verbose_name='মোট সেশন')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='ছুটির দিন')),
                ('is_generated', models.BooleanField(default=False, verbose_name='জেনারেট করা হয়েছে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_days', to='batches.batch', verbose_name='ব্যাচ')),
            ],
            options={
                'verbose_name': 'ব্যাচ ক্যালেন্ডার দিন',
                'verbose_name_plural': 'ব্যাচ ক্যালেন্ডার দিন',
                'ordering': ('date',),
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
