# Generated by Django 6.0.6 on 2026-06-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessors', '0003_assessor_education_and_more'),
        ('batches', '0006_batchcalendarday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAssessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(default='pre_evaluation', max_length=20, verbose_name='মূল্যায়নের ধরণ')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='নিয়োগের তারিখ')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='assessors.assessor', verbose_name='মূল্যায়নকারী')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_assignments', to='batches.batch', verbose_name='ব্যাচ')),
            ],
            options={
                'verbose_name': 'ব্যাচ-মূল্যায়নকারী নিয়োগ',
                'verbose_name_plural': 'ব্যাচ-মূল্যায়নকারী নিয়োগ',
                'ordering': ('-assigned_at',),
                'unique_together': {('batch', 'assessor')},
            },
        ),
    ]
