# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='সেশনের তারিখ')),
                ('session_no', models.PositiveIntegerField(verbose_name='সেশন নম্বর')),
                ('status', models.CharField(choices=[('present', 'উপস্থিত'), ('late', 'বিলম্বে'), ('absent', 'অনুপস্থিত'), ('leave', 'ছুটি')], default='present', max_length=10, verbose_name='অবস্থা')),
                ('guest_trainer_name', models.CharField(blank=True, max_length=255, verbose_name='অতিথি প্রশিক্ষকের নাম')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='মার্কের সময়')),
                ('remarks', models.TextField(blank=True, verbose_name='মন্তব্য')),
            ],
            options={
                'verbose_name': 'উপস্থিতি',
                'verbose_name_plural': 'উপস্থিতি',
                'ordering': ('-session_date', '-session_no'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='মোট সেশন')),
                ('attended_sessions', models.PositiveIntegerField(default=0, verbose_name='উপস্থিত সেশন')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='উপস্থিতির হার (%)')),
            ],
            options={
                'verbose_name': 'উপস্থিতি সারাংশ',
                'verbose_name_plural': 'উপস্থিতি সারাংশ',
            },
        ),
    ]
