# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0001_initial'),
        ('trainers', '0001_initial'),
        ('attendance', '0001_initial'),
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='batches.batch', verbose_name='ব্যাচ'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='trainees.trainee', verbose_name='প্রশিক্ষণার্থী'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='associate_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_associate', to='trainers.trainer', verbose_name='সহকারী প্রশিক্ষক'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='batches.batch', verbose_name='ব্যাচ'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lead_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_lead', to='trainers.trainer', verbose_name='প্রধান প্রশিক্ষক'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='মার্ক করেছেন'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='trainees.trainee', verbose_name='প্রশিক্ষণার্থী'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['batch', 'attendance_percentage'], name='attendance__batch_i_8e56cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('trainee', 'batch')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['batch', 'session_date'], name='attendance__batch_i_1ff922_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['trainee', 'batch'], name='attendance__trainee_a9c4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['batch', 'status'], name='attendance__batch_i_b0c81a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('trainee', 'batch', 'session_date', 'session_no')},
        ),
    ]
