# Generated by Django 5.0 on 2026-06-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesummary',
            name='attended_sessions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='উপস্থিত সেশন'),
        ),
    ]
