# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
        ('batches', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(db_index=True, max_length=20, verbose_name='আবেদন নম্বর')),
                ('trainee_registration_no', models.CharField(blank=True, max_length=30, verbose_name='রেজিস্ট্রেশন নম্বর')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='ব্যবহারকারীর ইমেইল')),
                ('result', models.CharField(choices=[('success', 'Success'), ('user_exists', 'User Already Exists'), ('failed', 'Failed')], default='failed', max_length=20, verbose_name='ফলাফল')),
                ('error_message', models.TextField(blank=True, verbose_name='ত্রুটির বিবরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'এনরোলমেন্ট অডিট লগ',
                'verbose_name_plural': 'এনরোলমেন্ট অডিট লগ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(editable=False, max_length=30, unique=True, verbose_name='রেজিস্ট্রেশন নম্বর')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='নথিভুক্তির তারিখ')),
                ('bank_account_no', models.CharField(blank=True, max_length=50, verbose_name='ব্যাংক অ্যাকাউন্ট নম্বর')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='ব্যাংকের নাম')),
                ('bank_branch', models.CharField(blank=True, max_length=255, verbose_name='ব্যাংক শাখা')),
                ('nominee_name', models.CharField(blank=True, max_length=255, verbose_name='মনোনীত ব্যক্তির নাম')),
                ('nominee_relation', models.CharField(blank=True, max_length=100, verbose_name='মনোনীত ব্যক্তির সম্পর্ক')),
                ('nominee_phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='ফোন নম্বর ১১ ডিজিটের হতে হবে এবং 01 দিয়ে শুরু হতে হবে', regex='^01\\d{9}$')], verbose_name='মনোনীত ব্যক্তির মোবাইল')),
                ('status', models.CharField(choices=[('enrolled', 'নথিভুক্ত'), ('dropped', 'বহিষ্কৃত'), ('completed', 'সমাপ্ত'), ('failed', 'ব্যর্থ')], default='enrolled', max_length=20, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_enrollment', to='applications.application', verbose_name='আবেদন')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='batches.batch', verbose_name='ব্যাচ')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='centers.center', verbose_name='প্রশিক্ষণ কেন্দ্র')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'প্রশিক্ষণার্থী',
                'verbose_name_plural': 'প্রশিক্ষণার্থীগণ',
                'ordering': ('-enrollment_date',),
                'indexes': [models.Index(fields=['center', 'status'], name='trainees_tr_center__fc2e76_idx'), models.Index(fields=['batch'], name='trainees_tr_batch_i_9d3b73_idx')],
            },
        ),
    ]
