# Generated by Django 5.0 on 2026-06-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='mobile_banking_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='মোবাইল ব্যাংকিং নম্বর'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='mobile_banking_provider',
            field=models.CharField(blank=True, choices=[('bkash', 'বিকাশ'), ('nagad', 'নগদ'), ('rocket', 'রকেট')], max_length=20, verbose_name='মোবাইল ব্যাংকিং'),
        ),
    ]
