# Generated by Django 5.0 on 2026-06-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='certificate_document',
            field=models.FileField(blank=True, null=True, upload_to='trainers/certificates/', verbose_name='সার্টিফিকেট ডকুমেন্ট'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='driving_license_document',
            field=models.FileField(blank=True, null=True, upload_to='trainers/driving_licenses/', verbose_name='ড্রাইভিং লাইসেন্স ডকুমেন্ট'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='driving_license_no',
            field=models.CharField(default='', max_length=50, verbose_name='ড্রাইভিং লাইসেন্স নং'),
        ),
        migrations.AddField(
            model_name='trainermapping',
            name='designation',
            field=models.CharField(default='', max_length=255, verbose_name='পদবী'),
        ),
    ]
