# Generated by Django 5.0 on 2026-06-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_certificate_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='education_qualification',
            field=models.TextField(blank=True, verbose_name='শিক্ষাগত যোগ্যতা'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='expertise_area',
            field=models.CharField(blank=True, max_length=255, verbose_name='দক্ষতার ক্ষেত্র'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=255, verbose_name='পিতার নাম (বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=255, verbose_name='মাতার নাম (বাংলায়)'),
        ),
    ]
