# Generated by Django 5.0 on 2026-06-12 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_master_data_models'),
        ('trainers', '0003_alter_trainer_education_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_config.education', verbose_name='শিক্ষাগত যোগ্যতা'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='education_qualification',
            field=models.TextField(blank=True, verbose_name='শিক্ষাগত যোগ্যতা (বিস্তারিত)'),
        ),
    ]
