# Generated by Django 6.0.6 on 2026-07-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_alter_actionlog_action'),
        ('courses', '0003_course_duration_unit_course_duration_value_and_more'),
        ('trainers', '0004_trainer_education_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainermapping',
            unique_together={('trainer', 'center')},
        ),
        migrations.AlterField(
            model_name='trainermapping',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_mappings', to='courses.course', verbose_name='কোর্স'),
        ),
    ]
