# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='বিষয়')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('channel', models.CharField(choices=[('email', 'ইমেইল'), ('sms', 'SMS'), ('both', 'উভয়')], default='email', max_length=10, verbose_name='চ্যানেল')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('sent', 'প্রেরিত'), ('failed', 'ব্যর্থ')], default='pending', max_length=10, verbose_name='অবস্থা')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='প্রেরণের সময়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='প্রাপক')),
            ],
            options={
                'verbose_name': 'বিজ্ঞপ্তি',
                'verbose_name_plural': 'বিজ্ঞপ্তিসমূহ',
                'ordering': ('-created_at',),
            },
        ),
    ]
