# Generated by Django 4.2.16 on 2026-05-08 12:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(default='02:00', help_text='HH:MM ফরম্যাটে', max_length=20, verbose_name='সময়সূচী')),
                ('retention_days', models.IntegerField(default=30, verbose_name='সংরক্ষণ দিন')),
                ('storage_path', models.CharField(default='backups/', max_length=500, verbose_name='স্টোরেজ পাথ')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='সর্বশেষ ব্যাকআপ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ব্যাকআপ কনফিগারেশন',
                'verbose_name_plural': 'ব্যাকআপ কনফিগারেশন',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='নাম')),
                ('subject_bn', models.CharField(max_length=255, verbose_name='বিষয় (বাংলা)')),
                ('subject_en', models.CharField(max_length=255, verbose_name='বিষয় (ইংরেজি)')),
                ('body_bn', ckeditor.fields.RichTextField(verbose_name='বডি (বাংলা)')),
                ('body_en', ckeditor.fields.RichTextField(verbose_name='বডি (ইংরেজি)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ইমেইল টেমপ্লেট',
                'verbose_name_plural': 'ইমেইল টেমপ্লেট',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='নাম')),
                ('message_bn', models.TextField(verbose_name='বার্তা (বাংলা)')),
                ('message_en', models.TextField(verbose_name='বার্তা (ইংরেজি)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'এসএমএস টেমপ্লেট',
                'verbose_name_plural': 'এসএমএস টেমপ্লেট',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='কী')),
                ('value', models.TextField(verbose_name='মান')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('float', 'Float')], default='string', max_length=20, verbose_name='ডাটা টাইপ')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='হালনাগাদের সময়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='হালনাগাদ করেছেন')),
            ],
            options={
                'verbose_name': 'সিস্টেম সেটিং',
                'verbose_name_plural': 'সিস্টেম সেটিংস',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='নাম')),
                ('provider', models.CharField(choices=[('nid_mock', 'NID Mock'), ('nid_live', 'NID Live'), ('sms_gateway', 'SMS Gateway'), ('payment_bkash', 'bKash'), ('payment_nagad', 'Nagad'), ('payment_rocket', 'Rocket'), ('email_smtp', 'SMTP Email')], max_length=50, verbose_name='প্রোভাইডার')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='সেটিংস')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='সর্বশেষ টেস্ট')),
                ('last_test_status', models.CharField(blank=True, max_length=20, verbose_name='সর্বশেষ টেস্ট অবস্থা')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='হালনাগাদ করেছেন')),
            ],
            options={
                'verbose_name': 'ইন্টিগ্রেশন কনফিগারেশন',
                'verbose_name_plural': 'ইন্টিগ্রেশন কনফিগারেশন',
                'ordering': ('name',),
            },
        ),
    ]
