# Generated by Django 5.0 on 2026-06-07 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100, unique=True, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='নাম (ইংরেজিতে)')),
                ('rank', models.IntegerField(default=0, help_text='শিক্ষাগত স্তর নির্ধারণের জন্য সংখ্যা', verbose_name='ক্রম/স্তর')),
                ('order', models.IntegerField(default=0, verbose_name='সজ্জা ক্রম')),
            ],
            options={
                'verbose_name': 'শিক্ষাগত যোগ্যতা',
                'verbose_name_plural': 'শিক্ষাগত যোগ্যতা',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=50, unique=True, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='নাম (ইংরেজিতে)')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'লিঙ্গ',
                'verbose_name_plural': 'লিঙ্গ',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=100, verbose_name='নাম (ইংরেজিতে)')),
                ('type', models.CharField(choices=[('division', 'বিভাগ'), ('district', 'জেলা'), ('upazila', 'উপজেলা')], max_length=20, verbose_name='ধরন')),
                ('bbs_code', models.CharField(blank=True, max_length=10, verbose_name='BBS কোড')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system_config.demography', verbose_name='প্যারেন্ট')),
            ],
            options={
                'verbose_name': 'জনসংখ্যা তথ্য',
                'verbose_name_plural': 'জনসংখ্যা তথ্য',
                'ordering': ('type', 'name_bn'),
                'unique_together': {('name_bn', 'type')},
            },
        ),
    ]
