import api from './api';

const hoService = {
  // Dashboard
  getSummary() { return api.get('/ho/dashboard/summary/'); },
  getCenterEnrollmentChart() { return api.get('/ho/dashboard/center_enrollment_chart/'); },
  getMonthlyRegistrations(months = 12) { return api.get(`/ho/dashboard/monthly_registrations/?months=${months}`); },
  getCompletionRate() { return api.get('/ho/dashboard/completion_rate/'); },
  getPlacementChart() { return api.get('/ho/dashboard/placement_chart/'); },
  getBatchStatusCounts() { return api.get('/ho/dashboard/batch_status_counts/'); },
  getCourseDemand() { return api.get('/ho/dashboard/course_demand/'); },
  getRecentActivity(days = 7) { return api.get(`/ho/dashboard/recent_activity/?days=${days}`); },
  getCenterPerformance() { return api.get('/ho/dashboard/center_performance/'); },
  getCharts(months = 12) { return api.get(`/ho/dashboard/charts/?months=${months}`); },
  getRecentActivities() { return api.get('/ho/dashboard/recent_activities/'); },

  // Centers (HO)
  listCenters(params) { return api.get('/ho/centers/', { params }); },
  getCenter(id) { return api.get(`/ho/centers/${id}/`); },
  createCenter(data) { return api.post('/ho/centers/', data); },
  updateCenter(id, data) { return api.put(`/ho/centers/${id}/`, data); },
  deleteCenter(id) { return api.delete(`/ho/centers/${id}/`); },
  toggleCenter(id) { return api.post(`/ho/centers/${id}/toggle/`); },
  getCenterStats(id) { return api.get(`/ho/centers/${id}/stats/`); },
  getCenterInfrastructure(id) { return api.get(`/ho/centers/${id}/infrastructure/`); },
  createInfrastructure(id, data) { return api.post(`/ho/centers/${id}/infrastructure/`, data); },
  updateInfrastructure(id, data) { return api.put(`/ho/infrastructures/${id}/`, data); },
  deleteInfrastructure(id) { return api.delete(`/ho/infrastructures/${id}/`); },
  getCenterEmployees(id) { return api.get(`/ho/centers/${id}/employees/`); },
  createEmployee(id, data) { return api.post(`/ho/centers/${id}/employees/`, data); },
  updateEmployee(id, data) { return api.put(`/ho/employees/${id}/`, data); },
  deleteEmployee(id) { return api.delete(`/ho/employees/${id}/`); },

  // Trainers (HO)
  listTrainers(params) { return api.get('/ho/trainers/', { params }); },
  getTrainer(id) { return api.get(`/ho/trainers/${id}/`); },
  getPendingTrainers() { return api.get('/ho/trainers/pending/'); },
  approveTrainer(id, data) { return api.post(`/ho/trainers/${id}/approve/`, data); },
  rejectTrainer(id, data) { return api.post(`/ho/trainers/${id}/reject/`, data); },
  suspendTrainer(id) { return api.post(`/ho/trainers/${id}/suspend/`); },
  activateTrainer(id) { return api.post(`/ho/trainers/${id}/activate/`); },
  blacklistTrainer(id) { return api.post(`/ho/trainers/${id}/blacklist/`); },
  trackTrainer(id) { return api.get(`/ho/trainers/${id}/track/`); },
  trackTrainerByNumber(trainerNo) { return api.get(`/ho/trainers/track_by_number/?trainer_no=${trainerNo}`); },
  trackTrainerByNid(nid) { return api.get(`/ho/trainers/track_by_nid/?nid=${nid}`); },
  trackTrainerByMobile(phone) { return api.get(`/ho/trainers/track_by_mobile/?phone=${phone}`); },
  trackTrainerByBcn(bcn) { return api.get(`/ho/trainers/track_by_bcn/?bcn=${bcn}`); },
  mapTrainer(data) { return api.post('/ho/trainers/map/', data); },
  unmapTrainer(id, mappingId) { return api.post(`/ho/trainers/${id}/unmap/`, { mapping_id: mappingId }); },
  exportTrainers(params) { return api.get('/ho/trainers/export/', { params }); },
  getTrainerCenters() { return api.get('/ho/trainers/centers/'); },
  getTrainerCourses(centerId) { return api.get(`/ho/trainers/courses/${centerId ? `?center_id=${centerId}` : ''}`); },
  approveMapping(id) { return api.post(`/ho/trainer-mappings/${id}/approve/`); },
  deleteTrainer(id) { return api.delete(`/ho/trainers/${id}/`); },

  // Assessors (HO)
  listAssessors(params) { return api.get('/ho/assessors/', { params }); },
  getAssessor(id) { return api.get(`/ho/assessors/${id}/`); },
  getPendingAssessors() { return api.get('/ho/assessors/pending/'); },
  approveAssessor(id, data) { return api.post(`/ho/assessors/${id}/approve/`, data); },
  rejectAssessor(id, data) { return api.post(`/ho/assessors/${id}/reject/`, data); },
  suspendAssessor(id) { return api.post(`/ho/assessors/${id}/suspend/`); },
  activateAssessor(id) { return api.post(`/ho/assessors/${id}/activate/`); },
  trackAssessor(id) { return api.get(`/ho/assessors/${id}/track/`); },
  trackAssessorByNumber(val) { return api.get(`/ho/assessors/track_by_number/?assessor_no=${val}`); },
  trackAssessorByNid(nid) { return api.get(`/ho/assessors/track_by_nid/?nid=${nid}`); },
  trackAssessorByMobile(phone) { return api.get(`/ho/assessors/track_by_mobile/?phone=${phone}`); },
  trackAssessorByBcn(bcn) { return api.get(`/ho/assessors/track_by_bcn/?bcn=${bcn}`); },
  mapAssessor(data) { return api.post('/ho/assessors/map/', data); },
  unmapAssessor(id, mappingId) { return api.post(`/ho/assessors/${id}/unmap/`, { mapping_id: mappingId }); },
  exportAssessors(params) { return api.get('/ho/assessors/export/', { params }); },
  getAssessorCenters() { return api.get('/ho/assessors/centers/'); },
  getAssessorCourses(centerId) { return api.get(`/ho/assessors/courses/${centerId ? `?center_id=${centerId}` : ''}`); },
  convertTrainerToAssessor(data) { return api.post('/ho/assessors/convert/', data); },
  searchConvertibleTrainers(q) { return api.get(`/ho/assessors/search_trainers/?q=${q}`); },
  approveAssessorMapping(id) { return api.post(`/ho/assessor-mappings/${id}/approve/`); },
  getAssessorBatches(id) { return api.get(`/ho/assessors/${id}/batches/`); },
  getAssessorAssessments(id) { return api.get(`/ho/assessors/${id}/assessments/`); },
  deleteAssessor(id) { return api.delete(`/ho/assessors/${id}/`); },

  // Applications (HO)
  listApplications(params) { return api.get('/applications/', { params }); },
  updateApplicationStatus(id, data) { return api.patch(`/applications/${id}/update_status/`, data); },

  // Courses (HO)
  listCourses(params) { return api.get('/ho/courses/', { params }); },
  getCourse(id) { return api.get(`/ho/courses/${id}/`); },
  createCourse(data) { return api.post('/ho/courses/', data); },
  updateCourse(id, data) { return api.put(`/ho/courses/${id}/`, data); },
  deleteCourse(id) { return api.delete(`/ho/courses/${id}/`); },
  activateCourse(id) { return api.post(`/ho/courses/${id}/activate/`); },
  deactivateCourse(id) { return api.post(`/ho/courses/${id}/deactivate/`); },
  getCourseConfiguration(id) { return api.get(`/ho/courses/${id}/configuration/`); },
  saveCourseConfiguration(id, data) { return api.post(`/ho/courses/${id}/configuration/`, data); },
  getCourseChapters(id) { return api.get(`/ho/courses/${id}/chapters/`); },
  addCourseChapter(id, data) { return api.post(`/ho/courses/${id}/chapters/`, data); },
  updateCourseChapter(id, data) { return api.put(`/ho/chapters/${id}/`, data); },
  deleteCourseChapter(id) { return api.delete(`/ho/chapters/${id}/`); },
  getCourseCompetencies(id) { return api.get(`/ho/courses/${id}/competency/`); },
  addCourseCompetency(id, data) { return api.post(`/ho/courses/${id}/competency/`, data); },
  deleteCourseCompetency(id) { return api.delete(`/ho/competencies/${id}/`); },
  getCourseBills(id) { return api.get(`/ho/courses/${id}/bill/`); },
  addCourseBill(id, data) { return api.post(`/ho/courses/${id}/bill/`, data); },
  deleteCourseBill(id) { return api.delete(`/ho/bills/${id}/`); },

  // Circulars (HO)
  listCirculars(params) { return api.get('/ho/circulars/', { params }); },
  getCircular(id) { return api.get(`/ho/circulars/${id}/`); },
  createCircular(data) { return api.post('/ho/circulars/', data); },
  updateCircular(id, data) { return api.put(`/ho/circulars/${id}/`, data); },
  deleteCircular(id) { return api.delete(`/ho/circulars/${id}/`); },
  publishCircular(id) { return api.post(`/ho/circulars/${id}/publish/`); },
  closeCircular(id) { return api.post(`/ho/circulars/${id}/close/`); },
  extendCircular(id, days) { return api.post(`/ho/circulars/${id}/extend/`, { days }); },
  getCircularAnalytics(id) { return api.get(`/ho/circulars/${id}/analytics/`); },
  getCircularApplications(id, params) { return api.get(`/ho/circulars/${id}/applications/`, { params }); },
  approveApplication(id, appId) { return api.post(`/ho/circulars/${id}/approve_application/`, { application_id: appId }); },
  rejectApplication(id, appId, remarks) { return api.post(`/ho/circulars/${id}/reject_application/`, { application_id: appId, remarks }); },
  getCircularStats() { return api.get('/ho/circulars/stats/'); },
  listActiveCirculars(params) { return api.get('/circulars/head-office/', { params }); },

  // Finance / Budgets
  listBudgets(params) { return api.get('/ho/finance/budgets/', { params }); },
  getBudget(id) { return api.get(`/ho/finance/budgets/${id}/`); },
  createBudget(data) { return api.post('/ho/finance/budgets/', data); },
  updateBudget(id, data) { return api.put(`/ho/finance/budgets/${id}/`, data); },
  deleteBudget(id) { return api.delete(`/ho/finance/budgets/${id}/`); },
  getBudgetUtilization(params) { return api.get('/ho/finance/budgets/utilization/', { params }); },

  // Finance / Vouchers
  listVouchers(params) { return api.get('/ho/finance/vouchers/', { params }); },
  getVoucher(id) { return api.get(`/ho/finance/vouchers/${id}/`); },
  createVoucher(data) { return api.post('/ho/finance/vouchers/', data); },
  verifyVoucher(id) { return api.put(`/ho/finance/vouchers/${id}/verify/`); },
  approveVoucher(id) { return api.put(`/ho/finance/vouchers/${id}/approve/`); },
  getSoEReport(params) { return api.get('/ho/finance/vouchers/soe/', { params }); },
  getTrialBalance() { return api.get('/ho/finance/vouchers/trial_balance/'); },
  getLedger(accountHead) { return api.get(`/ho/finance/vouchers/ledger/${encodeURIComponent(accountHead)}/`); },
  getVoucherStats() { return api.get('/ho/finance/vouchers/stats/'); },

  // Reports (async generator)
  listReports(params) { return api.get('/reports/', { params }); },
  generateReport(data) { return api.post('/reports/generate/', data); },
  getReportStatus(id) { return api.get(`/reports/${id}/status/`); },
  downloadReport(id) { return api.get(`/reports/${id}/download/`, { responseType: 'blob' }); },
  regenerateReport(id) { return api.post(`/reports/${id}/regenerate/`); },

  // Reports (HO - synchronous)
  getHOReport(type, params) { return api.get(`/ho/reports/${type}/`, { params }); },
  exportHOReport(type, params) { return api.get(`/ho/reports/${type}/`, { params, responseType: 'blob' }); },
  listReportTypes() { return api.get('/ho/reports/list_types/'); },

  // Scheduled Reports (HO)
  listScheduledReports() { return api.get('/ho/scheduled-reports/'); },
  createScheduledReport(data) { return api.post('/ho/scheduled-reports/', data); },
  updateScheduledReport(id, data) { return api.put(`/ho/scheduled-reports/${id}/`, data); },
  deleteScheduledReport(id) { return api.delete(`/ho/scheduled-reports/${id}/`); },

  // Batches (HO)
  listBatches(params) { return api.get('/ho/batches/', { params }).catch(() => ({ data: [] })); },

  // Users (HO)
  listHOUsers(params) { return api.get('/ho/users/', { params }); },
  getHOUser(id) { return api.get(`/ho/users/${id}/`); },
  createHOUser(data) { return api.post('/ho/users/', data); },
  updateHOUser(id, data) { return api.put(`/ho/users/${id}/`, data); },
  deleteHOUser(id) { return api.delete(`/ho/users/${id}/`); },
  toggleHOUser(id) { return api.post(`/ho/users/${id}/toggle_status/`); },
  resetPasswordHOUser(id, data) { return api.post(`/ho/users/${id}/reset_password/`, data); },
  resetMfaHOUser(id) { return api.post(`/ho/users/${id}/reset_mfa/`); },
  getLoginHistory(id) { return api.get(`/ho/users/${id}/login_history/`); },
  getUserAuditLog(id) { return api.get(`/ho/users/${id}/audit_log/`); },
  exportHOUsers(params) { return api.get('/ho/users/export/', { params, responseType: 'blob' }); },
  importHOUsers(formData) { return api.post('/ho/users/import_users/', formData); },

  // Roles (HO)
  listRoles() { return api.get('/ho/roles/'); },
  createRole(data) { return api.post('/ho/roles/', data); },
  updateRole(id, data) { return api.put(`/ho/roles/${id}/`, data); },
  deleteRole(id) { return api.delete(`/ho/roles/${id}/`); },
  updateRolePermissions(id, data) { return api.put(`/ho/roles/${id}/permissions/`, data); },
  listAvailablePermissions() { return api.get('/ho/roles/available_permissions/'); },

  // System Config
  getSystemSettings(params) { return api.get('/ho/system/settings/', { params }); },
  updateSystemSetting(key, data) { return api.put('/ho/system/settings/', data); },
  getEmailTemplates() { return api.get('/ho/system/email_templates/'); },
  updateEmailTemplate(id, data) { return api.put('/ho/system/email_templates/', data); },
  testEmailTemplate(id, data) { return api.post('/ho/system/email_templates_test/', data); },
  getSmsTemplates() { return api.get('/ho/system/sms_templates/'); },
  updateSmsTemplate(id, data) { return api.put('/ho/system/sms_templates/', data); },
  testSmsTemplate(id, data) { return api.post('/ho/system/sms_templates_test/', data); },
  getIntegrations() { return api.get('/ho/system/integrations/'); },
  updateIntegration(name, data) { return api.put('/ho/system/integrations/', data); },
  testIntegration(name, data) { return api.post('/ho/system/integrations_test/', data); },
  getSystemHealth() { return api.get('/ho/system/health/'); },
  triggerBackup() { return api.post('/ho/system/backup_now/'); },
  clearCache() { return api.post('/ho/system/clear_cache/'); },
};

export default hoService;
