# Generated by Django 4.2.16 on 2026-05-08 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0002_actionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True, verbose_name='ভাউচার নং')),
                ('voucher_type', models.CharField(choices=[('journal', 'জার্নাল'), ('payment', 'পেমেন্ট'), ('contra', 'কন্ট্রা')], default='journal', max_length=10, verbose_name='ভাউচারের ধরণ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='মোট অর্থ')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('verified', 'যাচাইকৃত'), ('approved', 'অনুমোদিত')], default='draft', max_length=10, verbose_name='অবস্থা')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('voucher_date', models.DateField(verbose_name='ভাউচারের তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='centers.center', verbose_name='কেন্দ্র')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
            ],
            options={
                'verbose_name': 'ভাউচার',
                'verbose_name_plural': 'ভাউচার',
                'ordering': ('-voucher_date',),
            },
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_head', models.CharField(max_length=255, verbose_name='হিসাব শিরোনাম')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ডেবিট')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ক্রেডিট')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='বিবরণ')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.voucher', verbose_name='ভাউচার')),
            ],
            options={
                'verbose_name': 'ভাউচার আইটেম',
                'verbose_name_plural': 'ভাউচার আইটেম',
            },
        ),
        migrations.CreateModel(
            name='MakerCheckerApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_date', models.DateTimeField(blank=True, null=True, verbose_name='নির্মাণের তারিখ')),
                ('checker_date', models.DateTimeField(blank=True, null=True, verbose_name='যাচাইয়ের তারিখ')),
                ('approver_date', models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের তারিখ')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='যাচাইকারী')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='নির্মাতা')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='finance.voucher', verbose_name='ভাউচার')),
            ],
            options={
                'verbose_name': 'নির্মাতা-যাচাইকারী-অনুমোদনকারী',
                'verbose_name_plural': 'নির্মাতা-যাচাইকারী-অনুমোদনকারী',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='যেমন: ২০২৪-২০২৫', max_length=9, verbose_name='অর্থবছর')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='বরাদ্দকৃত অর্থ')),
                ('expended_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ব্যয়িত অর্থ')),
                ('notes', models.TextField(blank=True, verbose_name='মন্তব্য')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='centers.center', verbose_name='কেন্দ্র')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='courses.course', verbose_name='কোর্স (ঐচ্ছিক)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
            ],
            options={
                'verbose_name': 'বাজেট',
                'verbose_name_plural': 'বাজেট',
                'ordering': ('-fiscal_year', 'center'),
                'unique_together': {('center', 'fiscal_year', 'course')},
            },
        ),
    ]
