# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0002_initial'),
        ('trainees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('self_employment', 'স্ব-কর্মসংস্থান'), ('wages_employment', 'মজুরি-কর্মসংস্থান'), ('up_skill_employment', 'আপ-স্কিল কর্মসংস্থান')], max_length=25, verbose_name='কর্মসংস্থানের ধরণ')),
                ('employer_name', models.CharField(max_length=255, verbose_name='নিয়োগকর্তার নাম')),
                ('employer_address', models.TextField(blank=True, verbose_name='নিয়োগকর্তার ঠিকানা')),
                ('designation_bn', models.CharField(max_length=255, verbose_name='পদবী (বাংলায়)')),
                ('designation_en', models.CharField(blank=True, max_length=255, verbose_name='পদবী (ইংরেজিতে)')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='বেতন')),
                ('start_date', models.DateField(verbose_name='শুরুর তারিখ')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='অবমুক্তির তারিখ')),
                ('is_current', models.BooleanField(default=True, verbose_name='বর্তমান চাকরি')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='যোগাযোগ ব্যক্তি')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='যোগাযোগের মোবাইল')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_placements', to='batches.batch', verbose_name='ব্যাচ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_placements_created', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_placements', to='trainees.trainee', verbose_name='প্রশিক্ষণার্থী')),
            ],
            options={
                'verbose_name': 'চাকরি স্থাপন',
                'verbose_name_plural': 'চাকরি স্থাপন',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_month', models.PositiveIntegerField(choices=[(3, '৩ মাস'), (6, '৬ মাস'), (12, '১২ মাস')], verbose_name='ট্র্যাকিং মাস')),
                ('tracking_date', models.DateField(verbose_name='ট্র্যাকিংয়ের তারিখ')),
                ('is_still_employed', models.BooleanField(default=True, verbose_name='এখনো কর্মরত')),
                ('salary_changed', models.BooleanField(default=False, verbose_name='বেতন পরিবর্তিত')),
                ('new_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='নতুন বেতন')),
                ('promoted', models.BooleanField(default=False, verbose_name='পদোন্নতি')),
                ('new_designation', models.CharField(blank=True, max_length=255, verbose_name='নতুন পদবী')),
                ('comments', models.TextField(blank=True, verbose_name='মন্তব্য')),
                ('tracked_at', models.DateTimeField(auto_now_add=True, verbose_name='ট্র্যাকিংয়ের সময়')),
                ('job_placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='jobplacement.jobplacement', verbose_name='চাকরি স্থাপন')),
                ('tracked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_trackings', to=settings.AUTH_USER_MODEL, verbose_name='ট্র্যাকিংকারী')),
            ],
            options={
                'verbose_name': 'চাকরি ট্র্যাকিং',
                'verbose_name_plural': 'চাকরি ট্র্যাকিং',
                'ordering': ('-tracking_date',),
                'indexes': [models.Index(fields=['job_placement', 'tracking_month'], name='jobplacemen_job_pla_fef973_idx')],
                'unique_together': {('job_placement', 'tracking_month')},
            },
        ),
        migrations.AddIndex(
            model_name='jobplacement',
            index=models.Index(fields=['batch', 'is_current'], name='jobplacemen_batch_i_c9b156_idx'),
        ),
        migrations.AddIndex(
            model_name='jobplacement',
            index=models.Index(fields=['trainee'], name='jobplacemen_trainee_aa0a46_idx'),
        ),
        migrations.AddIndex(
            model_name='jobplacement',
            index=models.Index(fields=['employment_type'], name='jobplacemen_employm_1d6fff_idx'),
        ),
    ]
