# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('trainees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateBatchZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(blank=True, upload_to='certificates/zips/', verbose_name='ZIP ফাইল')),
                ('total_certificates', models.PositiveIntegerField(default=0, verbose_name='মোট সার্টিফিকেট')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='সফল')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='ব্যর্থ')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='টাস্ক আইডি')),
                ('is_ready', models.BooleanField(default=False, verbose_name='প্রস্তুত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_zips', to='batches.batch', verbose_name='ব্যাচ')),
            ],
            options={
                'verbose_name': 'সার্টিফিকেট ZIP',
                'verbose_name_plural': 'সার্টিফিকেট ZIP',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='সার্টিফিকেট নং')),
                ('qr_code_url', models.TextField(blank=True, help_text='QR কোড ইমেজের URL', verbose_name='QR কোড URL')),
                ('qr_code_image', models.FileField(blank=True, upload_to='certificates/qrcodes/', verbose_name='QR কোড (ছবি)')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='ইস্যুর তারিখ')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/pdfs/', verbose_name='PDF ফাইল')),
                ('verification_url', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='যাচাইকরণ URL')),
                ('is_verified', models.BooleanField(default=False, verbose_name='যাচাইকৃত')),
                ('verified_count', models.PositiveIntegerField(default=0, verbose_name='যাচাইকরণ সংখ্যা')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='সর্বশেষ যাচাইকরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='batches.batch', verbose_name='ব্যাচ')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='trainees.trainee', verbose_name='প্রশিক্ষণার্থী')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL, verbose_name='যাচাইকারী')),
            ],
            options={
                'verbose_name': 'সার্টিফিকেট',
                'verbose_name_plural': 'সার্টিফিকেটসমূহ',
                'ordering': ('-issue_date',),
                'indexes': [models.Index(fields=['trainee', 'batch'], name='certificate_trainee_2b0981_idx'), models.Index(fields=['verification_url'], name='certificate_verific_1f1886_idx')],
            },
        ),
    ]
