# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='লগইনের জন্য ব্যবহার করা হবে', max_length=254, unique=True, verbose_name='ইমেইল')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='ব্যবহারকারীর নাম')),
                ('user_type', models.CharField(choices=[('head_office', 'হেড অফিস'), ('center_admin', 'কেন্দ্র প্রশাসক'), ('trainer', 'প্রশিক্ষক'), ('assessor', 'মূল্যায়নকারী'), ('trainee', 'প্রশিক্ষণার্থী')], default='trainee', max_length=20, verbose_name='ব্যবহারকারীর ধরণ')),
                ('full_name_bn', models.CharField(help_text='নিকোশ ফন্টে বাংলায় নাম লিখুন', max_length=255, verbose_name='নাম (বাংলায়)')),
                ('full_name_en', models.CharField(max_length=255, verbose_name='নাম (ইংরেজিতে)')),
                ('phone', models.CharField(help_text='১১ ডিজিটের মোবাইল নম্বর', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='মোবাইল নম্বর')),
                ('nid', models.CharField(help_text='১০ বা ১৭ ডিজিটের এনআইডি', max_length=17, unique=True, verbose_name='জাতীয় পরিচয়পত্র নং')),
                ('birth_certificate_no', models.CharField(blank=True, help_text='১৭ ডিজিটের জন্ম নিবন্ধন নম্বর (ঐচ্ছিক)', max_length=17, null=True, verbose_name='জন্ম নিবন্ধন নং')),
                ('profile_image', models.ImageField(blank=True, upload_to='users/profiles/', verbose_name='প্রোফাইল ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('mfa_secret', models.CharField(blank=True, help_text='টু-ফ্যাক্টর অথেনটিকেশনের জন্য সিক্রেট কী', max_length=64, null=True, verbose_name='MFA সিক্রেট')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='সর্বশেষ লগইন')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='তৈরির তারিখ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='স্টাফ স্ট্যাটাস')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='নিবন্ধনের তারিখ')),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী',
                'verbose_name_plural': 'ব্যবহারকারীগণ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name_bn', models.CharField(blank=True, max_length=255, verbose_name='পিতার নাম (বাংলায়)')),
                ('mother_name_bn', models.CharField(blank=True, max_length=255, verbose_name='মাতার নাম (বাংলায়)')),
                ('present_address', models.TextField(blank=True, verbose_name='বর্তমান ঠিকানা')),
                ('permanent_address', models.TextField(blank=True, verbose_name='স্থায়ী ঠিকানা')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='রক্তের গ্রুপ')),
                ('gender', models.CharField(blank=True, choices=[('male', 'পুরুষ'), ('female', 'মহিলা'), ('other', 'অন্যান্য')], max_length=10, verbose_name='লিঙ্গ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ')),
                ('emergency_contact', models.CharField(blank=True, max_length=11, verbose_name='জরুরি যোগাযোগ')),
                ('bio', models.TextField(blank=True, verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী প্রোফাইল',
                'verbose_name_plural': 'ব্যবহারকারী প্রোফাইল',
            },
        ),
    ]
