# Generated by Django 4.2.16 on 2026-05-08 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ভূমিকার নাম')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='অনুমতি')),
                ('is_system', models.BooleanField(default=False, verbose_name='সিস্টেম ভূমিকা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ভূমিকা',
                'verbose_name_plural': 'ভূমিকাসমূহ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='আইপি ঠিকানা')),
                ('user_agent', models.TextField(blank=True, verbose_name='ইউজার এজেন্ট')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='লগইনের সময়')),
                ('is_success', models.BooleanField(default=True, verbose_name='সফল')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'লগইন লগ',
                'verbose_name_plural': 'লগইন লগ',
                'ordering': ('-login_time',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='ভূমিকা'),
        ),
    ]
