# Generated by Django 4.2.16 on 2026-05-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_loginlog_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user_type',
            field=models.CharField(blank=True, default='', help_text='কোন ধরণের ব্যবহারকারীর জন্য এই ভূমিকা (খালি রাখলে সবার জন্য)', max_length=20, verbose_name='ব্যবহারকারীর ধরণ'),
        ),
    ]
