# Generated by Django 5.0 on 2026-06-12 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='মোবাইল নিশ্চিতকরণ'),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP কোড')),
                ('purpose', models.CharField(choices=[('registration', 'নিবন্ধন'), ('password_reset', 'পাসওয়ার্ড রিসেট')], default='registration', max_length=20, verbose_name='উদ্দেশ্য')),
                ('is_verified', models.BooleanField(default=False, verbose_name='নিশ্চিতকরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='মেয়াদ শেষ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'OTP নিশ্চিতকরণ',
                'verbose_name_plural': 'OTP নিশ্চিতকরণ',
                'ordering': ('-created_at',),
            },
        ),
    ]
