# Generated by Django 5.0 on 2026-06-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_phone_verified_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('head_office', 'হেড অফিস'), ('center_admin', 'কেন্দ্র প্রশাসক'), ('accountant', 'হিসাবরক্ষক'), ('trainer', 'প্রশিক্ষক'), ('assessor', 'মূল্যায়নকারী'), ('trainee', 'প্রশিক্ষণার্থী')], default='trainee', max_length=20, verbose_name='ব্যবহারকারীর ধরণ'),
        ),
    ]
