# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('pre_evaluation', 'পূর্ব-মূল্যায়ন'), ('written', 'লিখিত'), ('viva', 'মৌখিক'), ('practical', 'ব্যবহারিক'), ('final', 'চূড়ান্ত')], max_length=20, verbose_name='মূল্যায়নের ধরণ')),
                ('assessment_date', models.DateField(verbose_name='মূল্যায়নের তারিখ')),
                ('competency_status', models.CharField(choices=[('competent', 'দক্ষ'), ('not_competent', 'অদক্ষ'), ('absent', 'অনুপস্থিত')], max_length=20, verbose_name='দক্ষতার অবস্থা')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='প্রাপ্ত নম্বর')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='পূর্ণ নম্বর')),
                ('percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='শতাংশ')),
                ('remarks', models.TextField(blank=True, verbose_name='মন্তব্য')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='মূল্যায়নের সময়')),
                ('is_reassessment', models.BooleanField(default=False, verbose_name='পুনর্মূল্যায়ন')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_marks', to=settings.AUTH_USER_MODEL, verbose_name='মূল্যায়নকারী ব্যবহারকারী')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessors.assessor', verbose_name='মূল্যায়নকারী')),
            ],
            options={
                'verbose_name': 'মূল্যায়ন',
                'verbose_name_plural': 'মূল্যায়ন',
                'ordering': ('-assessment_date',),
            },
        ),
        migrations.CreateModel(
            name='Reassessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='পুনর্মূল্যায়নের কারণ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='অনুরোধের তারিখ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reassessments', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী')),
                ('new_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassessment_of', to='assessments.assessment', verbose_name='নতুন মূল্যায়ন')),
                ('original_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassessment_requests', to='assessments.assessment', verbose_name='মূল মূল্যায়ন')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reassessments', to=settings.AUTH_USER_MODEL, verbose_name='অনুরোধকারী')),
            ],
            options={
                'verbose_name': 'পুনর্মূল্যায়ন',
                'verbose_name_plural': 'পুনর্মূল্যায়ন',
                'ordering': ('-created_at',),
            },
        ),
    ]
