# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainees', '0001_initial'),
        ('batches', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='batches.batch', verbose_name='ব্যাচ'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='trainees.trainee', verbose_name='প্রশিক্ষণার্থী'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['batch', 'assessment_type'], name='assessments_batch_i_984a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['trainee', 'batch'], name='assessments_trainee_a2d85f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['competency_status'], name='assessments_compete_261fdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('trainee', 'batch', 'assessment_type', 'is_reassessment')},
        ),
    ]
