# Generated by Django 5.0 on 2026-06-13 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('trainees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=255, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=255, verbose_name='নাম (ইংরেজিতে)')),
                ('amount_per_session', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='প্রতি সেশনে ভাতা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allowance_categories', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
            ],
            options={
                'verbose_name': 'ভাতার শ্রেণী',
                'verbose_name_plural': 'ভাতার শ্রেণী',
            },
        ),
        migrations.CreateModel(
            name='TraineeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='মোট সেশন')),
                ('attended_sessions', models.PositiveIntegerField(default=0, verbose_name='উপস্থিত সেশন')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='গণনাকৃত অর্থ')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='অনুমোদিত অর্থ')),
                ('status', models.CharField(choices=[('calculated', 'গণনাকৃত'), ('approved', 'অনুমোদিত'), ('disbursed', 'বিতরণকৃত')], default='calculated', max_length=15, verbose_name='অবস্থা')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের তারিখ')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='বিতরণের তারিখ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allowances', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='batches.batch', verbose_name='ব্যাচ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='allowance.allowancecategory', verbose_name='ভাতার শ্রেণী')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_allowances', to=settings.AUTH_USER_MODEL, verbose_name='বিতরণকারী')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='trainees.trainee', verbose_name='প্রশিক্ষণার্থী')),
            ],
            options={
                'verbose_name': 'প্রশিক্ষণার্থী ভাতা',
                'verbose_name_plural': 'প্রশিক্ষণার্থী ভাতা',
                'unique_together': {('trainee', 'batch', 'category')},
            },
        ),
    ]
