# Generated by Django 5.0 on 2026-06-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancecategory',
            name='calculation_basis',
            field=models.CharField(choices=[('per_session', 'প্রতি সেশন'), ('tiered', 'স্তরভিত্তিক')], default='per_session', max_length=20, verbose_name='গণনার ধরন'),
        ),
        migrations.AlterField(
            model_name='traineeallowance',
            name='attended_sessions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='উপস্থিত সেশন'),
        ),
        migrations.CreateModel(
            name='AllowanceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=255, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='নাম (ইংরেজিতে)')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ন্যূনতম শতাংশ (%)')),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='সর্বোচ্চ শতাংশ (%)')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='গুণক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='allowance.allowancecategory', verbose_name='ভাতার শ্রেণী')),
            ],
            options={
                'verbose_name': 'ভাতার স্তর',
                'verbose_name_plural': 'ভাতার স্তর',
                'ordering': ('category', 'min_percentage'),
            },
        ),
    ]
