# Generated by Django 5.0 on 2026-06-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0002_allowancecategory_calculation_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeallowance',
            name='disbursement_notes',
            field=models.TextField(blank=True, verbose_name='বিতরণ নোট'),
        ),
        migrations.AddField(
            model_name='traineeallowance',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'বিকাশ'), ('nagad', 'নগদ'), ('bank', 'ব্যাংক'), ('cash', 'নগদ অর্থ')], max_length=20, verbose_name='পেমেন্ট পদ্ধতি'),
        ),
        migrations.AddField(
            model_name='traineeallowance',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='লেনদেন আইডি'),
        ),
    ]
