# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circulars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='Session ID')),
                ('front_image', models.CharField(blank=True, max_length=500, verbose_name='Front Image Path')),
                ('back_image', models.CharField(blank=True, max_length=500, verbose_name='Back Image Path')),
                ('extracted_nid', models.CharField(blank=True, max_length=20, verbose_name='Extracted NID')),
                ('extracted_name', models.CharField(blank=True, max_length=255, verbose_name='Extracted Name')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Confidence Score')),
                ('result', models.CharField(choices=[('success', 'Success'), ('low_confidence', 'Low Confidence'), ('failed', 'Failed')], default='failed', max_length=20, verbose_name='Result')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('raw_text_snippet', models.TextField(blank=True, verbose_name='Raw OCR Snippet')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OCR Audit Log',
                'verbose_name_plural': 'OCR Audit Logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='আবেদন নম্বর')),
                ('status', models.CharField(choices=[('pending', 'বিচারাধীন'), ('selected', 'নির্বাচিত'), ('rejected', 'বাতিল'), ('waitlisted', 'অপেক্ষমাণ')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('name_bn', models.CharField(max_length=255, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='নাম (ইংরেজিতে)')),
                ('father_name_bn', models.CharField(max_length=255, verbose_name='পিতার নাম')),
                ('mother_name_bn', models.CharField(max_length=255, verbose_name='মাতার নাম')),
                ('spouse_name_bn', models.CharField(blank=True, max_length=255, verbose_name='স্বামী/স্ত্রীর নাম')),
                ('date_of_birth', models.DateField(verbose_name='জন্ম তারিখ')),
                ('nid', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='জাতীয় পরিচয়পত্র নং')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='ফোন নম্বর ১১ ডিজিটের হতে হবে এবং 01 দিয়ে শুরু হতে হবে', regex='^01\\d{9}$')], verbose_name='মোবাইল নম্বর')),
                ('alternate_phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='ফোন নম্বর ১১ ডিজিটের হতে হবে এবং 01 দিয়ে শুরু হতে হবে', regex='^01\\d{9}$')], verbose_name='বিকল্প মোবাইল নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('present_address', models.TextField(verbose_name='বর্তমান ঠিকানা')),
                ('permanent_address', models.TextField(verbose_name='স্থায়ী ঠিকানা')),
                ('education_qualification', models.TextField(verbose_name='শিক্ষাগত যোগ্যতা')),
                ('profession', models.CharField(blank=True, max_length=255, verbose_name='পেশা')),
                ('profile_image', models.ImageField(blank=True, upload_to='applications/photos/', verbose_name='ছবি')),
                ('nid_front_image', models.ImageField(blank=True, upload_to='applications/nid/', verbose_name='এনআইডি (সামনে)')),
                ('nid_back_image', models.ImageField(blank=True, upload_to='applications/nid/', verbose_name='এনআইডি (পেছনে)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='পর্যালোচনার তারিখ')),
                ('remarks', models.TextField(blank=True, verbose_name='মন্তব্য')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='আবেদনের তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='হালনাগাদের তারিখ')),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='circulars.circular', verbose_name='সার্কুলার')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='পর্যালোচক')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'আবেদন',
                'verbose_name_plural': 'আবেদনসমূহ',
                'ordering': ('-applied_at',),
                'indexes': [models.Index(fields=['circular', 'status'], name='application_circula_1737c1_idx'), models.Index(fields=['nid'], name='application_nid_46006b_idx'), models.Index(fields=['applied_at'], name='application_applied_06e426_idx')],
            },
        ),
    ]
