# Generated by Django 5.0 on 2026-06-07 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('centers', '0002_actionlog'),
        ('circulars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='উত্তর')),
                ('is_pass', models.BooleanField(default=False, verbose_name='পাস')),
                ('score_achieved', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='প্রাপ্ত স্কোর')),
            ],
            options={
                'verbose_name': 'চেকলিস্ট উত্তর',
                'verbose_name_plural': 'চেকলিস্ট উত্তরসমূহ',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='auto_screen_pass',
            field=models.BooleanField(blank=True, help_text='True = স্বয়ংক্রিয় স্ক্রিনিং পাস করেছে, False = ব্যর্থ, Null = এখনো পরীক্ষা করা হয়নি', null=True, verbose_name='অটো-স্ক্রিন পাস'),
        ),
        migrations.AddField(
            model_name='application',
            name='auto_screen_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='অটো-স্ক্রিন স্কোর'),
        ),
        migrations.AddField(
            model_name='application',
            name='chosen_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='centers.center', verbose_name='নির্বাচিত কেন্দ্র'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['auto_screen_pass'], name='application_auto_sc_2da8c3_idx'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='applications.application', verbose_name='আবেদন'),
        ),
    ]
