# Generated by Django 5.0 on 2026-06-07 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_checklistresponse_application_auto_screen_pass_and_more'),
        ('circulars', '0002_checklistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulars.checklistitem', verbose_name='চেকলিস্ট আইটেম'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistresponse',
            unique_together={('application', 'checklist_item')},
        ),
    ]
