# Generated by Django 5.0 on 2026-06-07 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_checklistresponse_checklist_item_and_more'),
        ('system_config', '0002_master_data_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_config.education', verbose_name='শিক্ষাগত যোগ্যতা'),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_config.gender', verbose_name='লিঙ্গ'),
        ),
        migrations.AddField(
            model_name='application',
            name='permanent_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='system_config.demography', verbose_name='স্থায়ী জেলা'),
        ),
        migrations.AddField(
            model_name='application',
            name='permanent_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='system_config.demography', verbose_name='স্থায়ী বিভাগ'),
        ),
        migrations.AddField(
            model_name='application',
            name='present_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='system_config.demography', verbose_name='বর্তমান জেলা'),
        ),
        migrations.AddField(
            model_name='application',
            name='present_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='system_config.demography', verbose_name='বর্তমান বিভাগ'),
        ),
    ]
