# Generated by Django 5.0 on 2026-06-12 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_drop_old_text_fields'),
        ('centers', '0005_center_center_type_center_latitude_center_longitude_and_more'),
        ('circulars', '0005_circular_default_overflow_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='circulars.committee', verbose_name='নির্বাচন কমিটি'),
        ),
        migrations.AddField(
            model_name='application',
            name='committee_decision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='কমিটির সিদ্ধান্তের তারিখ'),
        ),
        migrations.AddField(
            model_name='application',
            name='committee_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_decisions', to=settings.AUTH_USER_MODEL, verbose_name='কমিটির সিদ্ধান্তকারী'),
        ),
        migrations.AddField(
            model_name='application',
            name='merit_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='চেকলিস্ট ভিত্তিক মোট মেধা স্কোর', max_digits=10, null=True, verbose_name='মেধা স্কোর'),
        ),
        migrations.AddField(
            model_name='application',
            name='routed_center',
            field=models.ForeignKey(blank=True, help_text='সিস্টেম কর্তৃক নির্ধারিত কেন্দ্র (chosen_center থেকে ভিন্ন হতে পারে)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_applications', to='centers.center', verbose_name='রুটিকৃত কেন্দ্র'),
        ),
        migrations.AddField(
            model_name='application',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='অপেক্ষমাণ অবস্থান'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'পেন্ডিং'), ('auto_rejected', 'স্বয়ংক্রিয়ভাবে বাতিল'), ('selected', 'নির্বাচিত'), ('rejected', 'বাতিল'), ('waitlisted', 'অপেক্ষমাণ'), ('enrolled', 'নথিভুক্ত')], default='pending', max_length=20, verbose_name='অবস্থা'),
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='লোড ফ্যাক্টর (%)')),
                ('priority_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='প্রাধান্য স্কোর')),
                ('reason', models.TextField(blank=True, verbose_name='কারণ')),
                ('routed_at', models.DateTimeField(auto_now_add=True, verbose_name='রুটিংয়ের তারিখ')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_logs', to='applications.application', verbose_name='আবেদন')),
                ('from_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_logs_from', to='centers.center', verbose_name='থেকে কেন্দ্র')),
                ('to_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_logs_to', to='centers.center', verbose_name='তে কেন্দ্র')),
            ],
            options={
                'verbose_name': 'রুটিং লগ',
                'verbose_name_plural': 'রুটিং লগসমূহ',
                'ordering': ('-routed_at',),
            },
        ),
        migrations.CreateModel(
            name='WaitlistHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='অবস্থান')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('promoted_at', models.DateTimeField(blank=True, null=True, verbose_name='উন্নীত হওয়ার তারিখ')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='মেয়াদ শেষের তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_history', to='applications.application', verbose_name='আবেদন')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_history', to='centers.center', verbose_name='কেন্দ্র')),
            ],
            options={
                'verbose_name': 'অপেক্ষমাণ ইতিহাস',
                'verbose_name_plural': 'অপেক্ষমাণ ইতিহাসসমূহ',
                'ordering': ('position',),
            },
        ),
    ]

