# Generated by Django 6.0.6 on 2026-06-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_committee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education_qualification',
            field=models.TextField(blank=True, verbose_name='শিক্ষাগত যোগ্যতা'),
        ),
        migrations.AlterField(
            model_name='application',
            name='permanent_address',
            field=models.TextField(blank=True, verbose_name='স্থায়ী ঠিকানা'),
        ),
    ]
