# Generated by Django 6.0.6 on 2026-07-19 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_education_qualification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeScreeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', 'অপেক্ষমান'), ('pass', 'পাস'), ('fail', 'ব্যর্থ')], default='pending', max_length=10, verbose_name='ফলাফল')),
                ('evidence_file', models.FileField(blank=True, upload_to='applications/eye_screening/', verbose_name='প্রমাণপত্র')),
                ('remarks', models.TextField(blank=True, help_text='ব্যর্থ হলে কারণ উল্লেখ করুন', verbose_name='কারণ')),
                ('tested_at', models.DateTimeField(blank=True, null=True, verbose_name='পরীক্ষার তারিখ')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eye_screening', to='applications.application', verbose_name='আবেদন')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_screening_tests', to=settings.AUTH_USER_MODEL, verbose_name='পরীক্ষক')),
            ],
            options={
                'verbose_name': 'চোখের দৃষ্টি পরীক্ষা',
                'verbose_name_plural': 'চোখের দৃষ্টি পরীক্ষাসমূহ',
            },
        ),
    ]
