# Generated by Django 6.0.6 on 2026-07-31 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_unique_nid_phone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='application_nid_46006b_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='nid',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='জাতীয় পরিচয়পত্র নং'),
        ),
        migrations.AlterField(
            model_name='application',
            name='nid_back_image',
            field=models.ImageField(blank=True, upload_to='applications/nid/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='এনআইডি (পেছনে)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='nid_front_image',
            field=models.ImageField(blank=True, upload_to='applications/nid/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='এনআইডি (সামনে)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='ফোন নম্বর ১১ ডিজিটের হতে হবে এবং 01 দিয়ে শুরু হতে হবে', regex='^01\\d{9}$')], verbose_name='মোবাইল নম্বর'),
        ),
        migrations.AlterField(
            model_name='application',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='applications/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='eyescreeningtest',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='applications/eye_screening/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='প্রমাণপত্র'),
        ),
    ]
