# Generated by Django 6.0.6 on 2026-08-09 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_unique_nid_phone_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NIDAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check_nid', 'Check NID'), ('verify_nid', 'Verify NID'), ('apply', 'Apply')], db_index=True, max_length=20, verbose_name='অ্যাকশন')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20, verbose_name='ফলাফল')),
                ('target_nid', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='টার্গেট এনআইডি')),
                ('target_name', models.CharField(blank=True, max_length=255, verbose_name='টার্গেটের নাম')),
                ('requester_name', models.CharField(blank=True, max_length=255, verbose_name='অনুরোধকারীর নাম')),
                ('requester_phone', models.CharField(blank=True, max_length=20, verbose_name='অনুরোধকারীর মোবাইল')),
                ('requester_address', models.TextField(blank=True, verbose_name='অনুরোধকারীর ঠিকানা')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request Path')),
                ('message', models.TextField(blank=True, verbose_name='বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='সময়')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nid_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'এনআইডি অ্যাক্সেস লগ',
                'verbose_name_plural': 'এনআইডি অ্যাক্সেস লগসমূহ',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_nid', 'created_at'], name='application_target__97ddb3_idx'), models.Index(fields=['action', 'result'], name='application_action_d00f66_idx')],
            },
        ),
    ]
