# Generated by Django 5.0.8 on 2026-08-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_nidaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_certificate',
            field=models.FileField(blank=True, upload_to='applications/certificates/', verbose_name='শিক্ষাগত সনদপত্র'),
        ),
        migrations.AddField(
            model_name='application',
            name='govt_job_certificate',
            field=models.FileField(blank=True, upload_to='applications/certificates/', verbose_name='সরকারি চাকুরির সনদপত্র'),
        ),
    ]
