# Generated by Django 4.2.16 on 2026-05-07 19:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='যেমন: DRV-FND-MRN-001', max_length=20, unique=True, verbose_name='কোর্স কোড')),
                ('name_bn', models.CharField(max_length=255, verbose_name='কোর্সের নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=255, verbose_name='কোর্সের নাম (ইংরেজিতে)')),
                ('course_type', models.CharField(choices=[('driver', 'ড্রাইভার'), ('mechanic', 'মেকানিক'), ('supervisor', 'সুপারভাইজার')], max_length=20, verbose_name='কোর্সের ধরণ')),
                ('term', models.CharField(choices=[('foundation', 'ফাউন্ডেশন'), ('advanced', 'এডভান্সড')], max_length=20, verbose_name='টার্ম')),
                ('session', models.CharField(choices=[('morning', 'সকাল'), ('day', 'দিন'), ('evening', 'সন্ধ্যা')], max_length=20, verbose_name='সেশন')),
                ('duration_months', models.PositiveIntegerField(verbose_name='মেয়াদ (মাস)')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='মোট ঘন্টা')),
                ('total_training_days', models.PositiveIntegerField(verbose_name='মোট প্রশিক্ষণ দিন')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='কোর্স ফি')),
                ('stipend_eligible', models.BooleanField(default=False, verbose_name='স্টাইপেন্ড উপযোগী')),
                ('employment_eligible', models.BooleanField(default=False, verbose_name='চাকরির উপযোগী')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ইউনিট খরচ')),
                ('total_target', models.PositiveIntegerField(default=0, verbose_name='মোট টার্গেট')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='বর্ণনা')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('active', 'সক্রিয়'), ('completed', 'সমাপ্ত')], default='draft', max_length=20, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
            ],
            options={
                'verbose_name': 'কোর্স',
                'verbose_name_plural': 'কোর্সসমূহ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_criteria', ckeditor.fields.RichTextField(blank=True, verbose_name='যোগ্যতার মানদণ্ড')),
                ('training_methodology', ckeditor.fields.RichTextField(blank=True, verbose_name='প্রশিক্ষণ পদ্ধতি')),
                ('assessment_criteria', ckeditor.fields.RichTextField(blank=True, verbose_name='মূল্যায়নের মানদণ্ড')),
                ('passing_marks', models.PositiveIntegerField(default=80, verbose_name='পাস মার্কস (%)')),
                ('attendance_requirement', models.PositiveIntegerField(default=80, verbose_name='উপস্থিতির প্রয়োজন (%)')),
                ('certificate_template', models.CharField(blank=True, max_length=255, verbose_name='সার্টিফিকেট টেমপ্লেট')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='courses.course', verbose_name='কোর্স')),
            ],
            options={
                'verbose_name': 'কোর্স কনফিগারেশন',
                'verbose_name_plural': 'কোর্স কনফিগারেশন',
            },
        ),
        migrations.CreateModel(
            name='CourseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_item_bn', models.CharField(max_length=255, verbose_name='বিল আইটেম (বাংলায়)')),
                ('bill_item_en', models.CharField(max_length=255, verbose_name='বিল আইটেম (ইংরেজিতে)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='পরিমাণ')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='বাধ্যতামূলক')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='courses.course', verbose_name='কোর্স')),
            ],
            options={
                'verbose_name': 'কোর্স বিল',
                'verbose_name_plural': 'কোর্স বিলসমূহ',
                'ordering': ('course', 'bill_item_en'),
            },
        ),
        migrations.CreateModel(
            name='UnitOfCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='কম্পিটেন্সি কোড')),
                ('name_bn', models.CharField(max_length=255, verbose_name='নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=255, verbose_name='নাম (ইংরেজিতে)')),
                ('assessment_method', models.CharField(blank=True, max_length=255, verbose_name='মূল্যায়ন পদ্ধতি')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='courses.course', verbose_name='কোর্স')),
            ],
            options={
                'verbose_name': 'কম্পিটেন্সি ইউনিট',
                'verbose_name_plural': 'কম্পিটেন্সি ইউনিটসমূহ',
                'ordering': ('course', 'code'),
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.PositiveIntegerField(verbose_name='অধ্যায় নম্বর')),
                ('title_bn', models.CharField(max_length=255, verbose_name='শিরোনাম (বাংলায়)')),
                ('title_en', models.CharField(max_length=255, verbose_name='শিরোনাম (ইংরেজিতে)')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='সময় (ঘন্টা)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='কোর্স')),
            ],
            options={
                'verbose_name': 'কোর্স অধ্যায়',
                'verbose_name_plural': 'কোর্স অধ্যায়সমূহ',
                'ordering': ('course', 'chapter_no'),
                'unique_together': {('course', 'chapter_no')},
            },
        ),
    ]
