# Generated by Django 5.0 on 2026-06-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='session',
            field=models.CharField(blank=True, choices=[('morning', 'সকাল'), ('day', 'দিন'), ('evening', 'সন্ধ্যা')], max_length=20, null=True, verbose_name='সেশন'),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, choices=[('foundation', 'ফাউন্ডেশন'), ('advanced', 'এডভান্সড')], max_length=20, null=True, verbose_name='টার্ম'),
        ),
    ]
