# Generated by Django 5.0 on 2026-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_session_alter_course_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'দিন'), ('weeks', 'সপ্তাহ'), ('months', 'মাস')], default='months', max_length=10, verbose_name='মেয়াদ একক'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_value',
            field=models.PositiveIntegerField(default=3, verbose_name='মেয়াদ মান'),
        ),
        migrations.AddField(
            model_name='course',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='প্রকল্পের নাম'),
        ),
        migrations.AddField(
            model_name='course',
            name='project_sponsor',
            field=models.CharField(blank=True, max_length=255, verbose_name='প্রকল্পের স্পনসর'),
        ),
    ]
