# Generated by Django 5.0.8 on 2026-08-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_unit_course_duration_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='form_type',
            field=models.CharField(blank=True, default='training', max_length=50, verbose_name='ফর্মের ধরণ'),
        ),
        migrations.AddField(
            model_name='course',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='প্রকল্পের কোড'),
        ),
    ]
