# Generated by Django 5.0.8 on 2026-08-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_form_type_course_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='মোট ঘন্টা'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_months',
            field=models.PositiveIntegerField(default=0, verbose_name='মেয়াদ (মাস)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='কোর্স ফি'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_training_days',
            field=models.PositiveIntegerField(default=0, verbose_name='মোট প্রশিক্ষণ দিন'),
        ),
    ]
