# Generated by Django 5.0.8 on 2026-08-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_duration_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='কোর্সের নাম (ইংরেজিতে)'),
        ),
    ]
