import io
import csv
from datetime import date, timedelta
from collections import OrderedDict, defaultdict
from decimal import Decimal

from django.db.models import Count, Sum, Avg, Q, F, Value, Case, When, IntegerField
from django.db.models.functions import TruncMonth, Coalesce
from django.utils import timezone

from apps.centers.models import Center, ActionLog
from apps.courses.models import Course
from apps.trainers.models import Trainer
from apps.assessors.models import Assessor
from apps.batches.models import Batch
from apps.attendance.models import Attendance
from apps.assessments.models import Assessment
from apps.certificates.models import Certificate
from apps.jobplacement.models import JobPlacement
from apps.applications.models import Application
from apps.circulars.models import Circular
from apps.trainees.models import Trainee
from apps.finance.models import Budget, Voucher
from apps.accounts.models import User, UserProfile


class ReportExporter:
    @staticmethod
    def to_csv(headers, rows):
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(headers)
        for row in rows:
            writer.writerow(row)
        return output.getvalue().encode('utf-8-sig')

    @staticmethod
    def to_excel(headers, rows, sheet_name='Report'):
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = sheet_name
        ws.append(headers)
        for row in rows:
            ws.append(row)
        output = io.BytesIO()
        wb.save(output)
        output.seek(0)
        return output.getvalue()

    @staticmethod
    def to_pdf(title, headers, rows, subtitle=''):
        import weasyprint
        html = '<!DOCTYPE html><html><head><meta charset="utf-8"><style>'
        html += '''
        body { font-family: 'Nikosh', sans-serif; font-size: 11px; padding: 20px; }
        h2 { text-align: center; margin-bottom: 5px; }
        .subtitle { text-align: center; color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #0d6efd; color: white; padding: 8px; text-align: left; }
        td { padding: 6px; border-bottom: 1px solid #dee2e6; }
        tr:nth-child(even) { background: #f8f9fa; }
        .footer { text-align: center; margin-top: 20px; color: #999; font-size: 10px; }
        </style></head><body>
        <h2>''' + title + '''</h2>
        <div class="subtitle">''' + subtitle + '''</div>
        <table><thead><tr>'''
        for h in headers:
            html += '<th>' + str(h) + '</th>'
        html += '</tr></thead><tbody>'
        for row in rows:
            html += '<tr>'
            for cell in row:
                html += '<td>' + str(cell) + '</td>'
            html += '</tr>'
        html += '</tbody></table>'
        html += '<div class="footer">Generated by BRTC TMS | ' + str(date.today()) + '</div>'
        html += '</body></html>'
        pdf_bytes = weasyprint.HTML(string=html).write_pdf()
        return pdf_bytes


class ReportGenerator:
    def __init__(self, params=None):
        self.params = params or {}
        self._apply_date_filters()

    def _apply_date_filters(self):
        self.date_from = self.params.get('from_date')
        self.date_to = self.params.get('to_date')
        self.center_ids = self.params.get('centers')
        self.course_ids = self.params.get('courses')
        self.batch_ids = self.params.get('batches')

        if isinstance(self.center_ids, str):
            self.center_ids = [int(x) for x in self.center_ids.split(',') if x]

    def _center_filter(self, field='center_id'):
        q = Q()
        if self.center_ids:
            q &= Q(**{f'{field}__in': self.center_ids})
        return q

    def _course_filter(self, field='course_id'):
        q = Q()
        if self.course_ids:
            q &= Q(**{f'{field}__in': self.course_ids})
        return q

    def _batch_filter(self, field='batch_id'):
        q = Q()
        if self.batch_ids:
            q &= Q(**{f'{field}__in': self.batch_ids})
        return q

    # ── Report 1: Center Performance ──────────────────────────────────────

    def center_wise(self):
        centers = Center.objects.filter(status='active')
        rows = []
        for c in centers:
            batches = Batch.objects.filter(center=c)
            if self.batch_ids:
                batches = batches.filter(id__in=self.batch_ids)
            total_batches = batches.count()
            trainees = Trainee.objects.filter(center=c)
            total_trainees = trainees.count()
            completed = batches.filter(status='completed').count()
            running = batches.filter(status='running').count()
            placements = JobPlacement.objects.filter(batch__center=c)
            placed = placements.count()
            placement_rate = round(placed / total_trainees * 100, 1) if total_trainees else 0
            budget = Budget.objects.filter(center=c).aggregate(
                allocated=Sum('allocated_amount'), expended=Sum('expended_amount'),
            )
            rows.append([
                c.code, c.name_bn, total_batches, running, completed,
                total_trainees, placed, f'{placement_rate}%',
                str(budget['allocated'] or 0), str(budget['expended'] or 0),
            ])
        return {
            'title': 'Center Performance Report',
            'headers': ['Code', 'Name', 'Total Batches', 'Running', 'Completed',
                        'Total Trainees', 'Placed', 'Placement Rate',
                        'Budget (Allocated)', 'Budget (Expended)'],
            'rows': rows,
        }

    # ── Report 2: Course Completion ───────────────────────────────────────

    def course_wise(self):
        courses = Course.objects.filter(status='active')
        rows = []
        for c in courses:
            batches = Batch.objects.filter(course=c)
            if self.batch_ids:
                batches = batches.filter(id__in=self.batch_ids)
            total_batches = batches.count()
            total_enrolled = Trainee.objects.filter(batch__course=c).count()
            completed = Trainee.objects.filter(batch__course=c, status='completed').count()
            dropped = Trainee.objects.filter(batch__course=c, status='dropped').count()
            failed = Trainee.objects.filter(batch__course=c, status='failed').count()
            completion_rate = round(completed / total_enrolled * 100, 1) if total_enrolled else 0
            rows.append([
                c.code, c.name_bn, c.course_type, c.term,
                total_batches, total_enrolled, completed, dropped, failed,
                f'{completion_rate}%',
            ])
        return {
            'title': 'Course Completion Report',
            'headers': ['Code', 'Name', 'Type', 'Term',
                        'Batches', 'Enrolled', 'Completed', 'Dropped', 'Failed', 'Completion Rate'],
            'rows': rows,
        }

    # ── Report 3: Trainer Performance ─────────────────────────────────────

    def trainer_performance(self):
        trainers = Trainer.objects.filter(approval_status='approved')
        rows = []
        for t in trainers:
            attended = Attendance.objects.filter(
                Q(lead_trainer=t) | Q(associate_trainer=t),
            )
            if self.date_from:
                attended = attended.filter(session_date__gte=self.date_from)
            if self.date_to:
                attended = attended.filter(session_date__lte=self.date_to)
            session_count = attended.count()
            trained_trainees = Trainee.objects.filter(
                batch__in=Batch.objects.filter(
                    id__in=attended.values_list('batch_id', flat=True),
                ),
            ).count()
            rows.append([
                t.trainer_no, t.user.full_name_bn, t.expertise_area,
                t.years_of_experience, session_count, trained_trainees,
            ])
        return {
            'title': 'Trainer Performance Report',
            'headers': ['ID', 'Name', 'Expertise', 'Experience (Yrs)', 'Sessions Taken', 'Trainees Taught'],
            'rows': rows,
        }

    # ── Report 4: Assessor Performance ────────────────────────────────────

    def assessor_performance(self):
        assessors = Assessor.objects.filter(approval_status='approved')
        rows = []
        for a in assessors:
            assessments = Assessment.objects.filter(assessor=a)
            if self.date_from:
                assessments = assessments.filter(assessment_date__gte=self.date_from)
            if self.date_to:
                assessments = assessments.filter(assessment_date__lte=self.date_to)
            total = assessments.count()
            competent = assessments.filter(competency_status='competent').count()
            not_competent = assessments.filter(competency_status='not_competent').count()
            avg_score = assessments.aggregate(avg=Avg('percentage'))['avg'] or 0
            pass_rate = round(competent / total * 100, 1) if total else 0
            rows.append([
                a.assessor_no, a.user.full_name_bn, a.expertise_area,
                total, competent, not_competent, f'{round(avg_score, 1)}%', f'{pass_rate}%',
            ])
        return {
            'title': 'Assessor Performance Report',
            'headers': ['ID', 'Name', 'Expertise', 'Assessments', 'Competent',
                        'Not Competent', 'Avg Score', 'Pass Rate'],
            'rows': rows,
        }

    # ── Report 5: Trainee Demographics ────────────────────────────────────

    def trainee_demographics(self):
        trainees = Trainee.objects.all()
        if self.center_ids:
            trainees = trainees.filter(center_id__in=self.center_ids)
        total = trainees.count()
        age_groups = {'18-25': 0, '26-35': 0, '36-45': 0, '46+': 0}
        today = date.today()
        genders = {'male': 0, 'female': 0, 'other': 0}
        for t in trainees:
            try:
                profile = t.user.profile
                if profile.gender in genders:
                    genders[profile.gender] += 1
                if profile.date_of_birth:
                    age = today.year - profile.date_of_birth.year
                    if age <= 25: age_groups['18-25'] += 1
                    elif age <= 35: age_groups['26-35'] += 1
                    elif age <= 45: age_groups['36-45'] += 1
                    else: age_groups['46+'] += 1
            except UserProfile.DoesNotExist:
                pass
        rows = [
            ['Total Trainees', total],
            ['Men', genders['male']],
            ['Women', genders['female']],
            ['Age 18-25', age_groups['18-25']],
            ['Age 26-35', age_groups['26-35']],
            ['Age 36-45', age_groups['36-45']],
            ['Age 46+', age_groups['46+']],
        ]
        return {
            'title': 'Trainee Demographics Report',
            'headers': ['Category', 'Count'],
            'rows': rows,
        }

    # ── Report 6: Attendance Compliance ───────────────────────────────────

    def attendance_compliance(self):
        centers = Center.objects.filter(status='active')
        rows = []
        for c in centers:
            batches = Batch.objects.filter(center=c, status__in=('running', 'completed'))
            if self.batch_ids:
                batches = batches.filter(id__in=self.batch_ids)
            total_sessions = 0
            total_attended = 0
            for b in batches:
                atts = Attendance.objects.filter(batch=b)
                total_sessions += atts.count()
                total_attended += atts.filter(status__in=('present', 'late')).count()
            rate = round(total_attended / total_sessions * 100, 1) if total_sessions else 0
            compliance = 'Compliant' if rate >= 80 else 'Non-Compliant'
            rows.append([c.code, c.name_bn, total_sessions, total_attended, f'{rate}%', compliance])
        rows = [r for r in rows if r[4].replace('%', '') and float(r[4].replace('%', '')) < 80]
        return {
            'title': 'Attendance Compliance Report (Below 80%)',
            'headers': ['Code', 'Center', 'Total Sessions', 'Attended', 'Rate', 'Status'],
            'rows': rows,
        }

    # ── Report 7: Assessment (Pass/Fail) ──────────────────────────────────

    def assessment(self):
        q = Q()
        if self.date_from:
            q &= Q(assessment_date__gte=self.date_from)
        if self.date_to:
            q &= Q(assessment_date__lte=self.date_to)
        if self.batch_ids:
            q &= Q(batch_id__in=self.batch_ids)
        assessments = Assessment.objects.filter(q).select_related('batch__course', 'trainee')
        total = assessments.count()
        pass_count = assessments.filter(competency_status='competent').count()
        fail_count = assessments.filter(competency_status='not_competent').count()
        absent = assessments.filter(competency_status='absent').count()
        pass_rate = round(pass_count / total * 100, 1) if total else 0
        avg_score = assessments.aggregate(avg=Avg('percentage'))['avg'] or 0
        by_type = assessments.values('assessment_type').annotate(
            total=Count('id'),
            passed=Count('id', filter=Q(competency_status='competent')),
            avg_marks=Avg('marks_obtained'),
        )
        rows = [
            ['Total Assessments', total],
            ['Passed (Competent)', pass_count],
            ['Failed (Not Competent)', fail_count],
            ['Absent', absent],
            ['Pass Rate', f'{pass_rate}%'],
            ['Average Score', f'{round(avg_score, 1)}%'],
        ]
        for bt in by_type:
            rows.append([f'  {bt["assessment_type"]}', f'{bt["total"]} (Passed: {bt["passed"]})'])
        return {
            'title': 'Assessment Report (Pass/Fail)',
            'headers': ['Metric', 'Value'],
            'rows': rows,
        }

    # ── Report 8: Certificate Issuance ────────────────────────────────────

    def certificate(self):
        q = Q()
        if self.date_from:
            q &= Q(issue_date__gte=self.date_from)
        if self.date_to:
            q &= Q(issue_date__lte=self.date_to)
        certs = Certificate.objects.filter(q).select_related('batch__center', 'batch__course', 'trainee')
        total = certs.count()
        verified = certs.filter(is_verified=True).count()
        centers = certs.values('batch__center__code', 'batch__center__name_bn').annotate(
            count=Count('id'),
        )
        rows = [
            ['Total Issued', total],
            ['Verified', verified],
            ['Pending Verification', total - verified],
        ]
        for c in centers:
            rows.append([f'  {c["batch__center__code"]} - {c["batch__center__name_bn"]}', c['count']])
        return {
            'title': 'Certificate Issuance Report',
            'headers': ['Category', 'Count'],
            'rows': rows,
        }

    # ── Report 9: Job Placement ──────────────────────────────────────────

    def job_placement(self):
        q = Q()
        placements = JobPlacement.objects.filter(q).select_related('batch__center', 'batch__course', 'trainee')
        total = placements.count()
        by_type = placements.values('employment_type').annotate(count=Count('id'))
        by_center = placements.values('batch__center__code', 'batch__center__name_bn').annotate(
            count=Count('id'), avg_salary=Avg('salary'),
        )
        avg_salary = placements.aggregate(avg=Avg('salary'))['avg'] or 0
        rows = [
            ['Total Placements', total],
            ['Average Salary', f'৳{round(avg_salary, 0)}'],
        ]
        for bt in by_type:
            rows.append([f'  Type: {bt["employment_type"]}', bt['count']])
        for bc in by_center:
            rows.append([
                f'  {bc["batch__center__code"]} - {bc["batch__center__name_bn"]}',
                f'{bc["count"]} (Avg Salary: ৳{round(bc["avg_salary"] or 0, 0)})',
            ])
        return {
            'title': 'Job Placement Report',
            'headers': ['Category', 'Value'],
            'rows': rows,
        }

    # ── Report 10: Financial SoE ─────────────────────────────────────────

    def financial_soe(self):
        q = Q(status='approved')
        if self.date_from:
            q &= Q(voucher_date__gte=self.date_from)
        if self.date_to:
            q &= Q(voucher_date__lte=self.date_to)
        if self.center_ids:
            q &= Q(center_id__in=self.center_ids)
        vouchers = Voucher.objects.filter(q).select_related('center').order_by('voucher_date')
        rows = []
        for v in vouchers:
            rows.append([
                v.voucher_date, v.voucher_no, v.description or '-',
                str(v.amount), v.center.name_bn if v.center else '-',
                v.get_voucher_type_display(),
            ])
        total = vouchers.aggregate(s=Sum('amount'))['s'] or 0
        rows.append(['', '', 'TOTAL:', str(total), '', ''])
        return {
            'title': 'Statement of Expenditure',
            'headers': ['Date', 'Voucher No', 'Description', 'Amount', 'Center', 'Type'],
            'rows': rows,
        }

    # ── Report 11: Budget vs Actual ──────────────────────────────────────

    def budget_vs_actual(self):
        q = Q()
        if self.center_ids:
            q &= Q(center_id__in=self.center_ids)
        budgets = Budget.objects.filter(q).select_related('center')
        rows = []
        for b in budgets:
            util = round(b.expended_amount / b.allocated_amount * 100, 1) if b.allocated_amount else 0
            rows.append([
                b.center.code, b.center.name_bn, b.fiscal_year,
                str(b.allocated_amount), str(b.expended_amount),
                f'{util}%',
                'Over Budget' if util > 100 else 'On Track' if util < 90 else 'Warning',
            ])
        return {
            'title': 'Budget vs Actual Report',
            'headers': ['Center Code', 'Center', 'Fiscal Year', 'Allocated', 'Expended', 'Utilization', 'Status'],
            'rows': rows,
        }

    # ── Report 12: Batch Completion ──────────────────────────────────────

    def batch_completion(self):
        q = Q()
        if self.center_ids:
            q &= Q(center_id__in=self.center_ids)
        if self.course_ids:
            q &= Q(course_id__in=self.course_ids)
        batches = Batch.objects.filter(q).select_related('center', 'course').order_by('-created_at')
        rows = []
        for b in batches:
            trainees = Trainee.objects.filter(batch=b)
            total = trainees.count()
            completed = trainees.filter(status='completed').count()
            dropped = trainees.filter(status='dropped').count()
            cr = round(completed / total * 100, 1) if total else 0
            rows.append([
                b.batch_no, b.batch_name_bn, b.center.code,
                b.course.code, b.start_date, b.end_date,
                b.get_status_display(), total, completed, dropped, f'{cr}%',
            ])
        return {
            'title': 'Batch Completion Report',
            'headers': ['Batch No', 'Name', 'Center', 'Course', 'Start', 'End',
                        'Status', 'Trainees', 'Completed', 'Dropped', 'Completion Rate'],
            'rows': rows,
        }

    # ── Report 13: Application Funnel ────────────────────────────────────

    def application_funnel(self):
        q = Q()
        if self.center_ids:
            q &= Q(circular__center_id__in=self.center_ids)
        apps = Application.objects.filter(q)
        total = apps.count()
        pending = apps.filter(status='pending').count()
        selected = apps.filter(status='selected').count()
        rejected = apps.filter(status='rejected').count()
        waitlisted = apps.filter(status='waitlisted').count()
        conversion = round(selected / total * 100, 1) if total else 0
        rows = [
            ['Total Applications', total],
            ['Pending', pending, f'{round(pending/total*100, 1) if total else 0}%'],
            ['Selected', selected, f'{round(selected/total*100, 1) if total else 0}%'],
            ['Rejected', rejected, f'{round(rejected/total*100, 1) if total else 0}%'],
            ['Waitlisted', waitlisted, f'{round(waitlisted/total*100, 1) if total else 0}%'],
            ['Conversion Rate', f'{conversion}%', ''],
        ]
        return {
            'title': 'Application Funnel Report',
            'headers': ['Stage', 'Count', 'Percentage'],
            'rows': rows,
        }

    # ── Report 14: Revenue (Fee Collection) ──────────────────────────────

    def revenue(self):
        q = Q()
        circulars = Circular.objects.filter(q).exclude(fee__isnull=True).exclude(fee=0)
        total_fee = circulars.aggregate(s=Sum('fee'))['s'] or 0
        total_seats = circulars.aggregate(s=Sum('total_seats'))['s'] or 0
        filled_seats = circulars.aggregate(s=Sum(
            F('total_seats') - F('remaining_seats'),
        ))['s'] or 0
        est_revenue = total_fee * filled_seats
        rows = [
            ['Total Circulars with Fees', circulars.count()],
            ['Total Seats Offered', total_seats],
            ['Filled Seats', filled_seats],
            ['Fee per Seat (Avg)', f'৳{round(total_fee / circulars.count() if circulars.count() else 0, 0)}'],
            ['Estimated Revenue', f'৳{est_revenue}'],
        ]
        return {
            'title': 'Revenue Report',
            'headers': ['Metric', 'Value'],
            'rows': rows,
        }

    # ── Report 15: Gender Diversity ──────────────────────────────────────

    def gender_diversity(self):
        centers = Center.objects.filter(status='active')
        rows = []
        grand_male = grand_female = 0
        for c in centers:
            trainees = Trainee.objects.filter(center=c)
            male = female = 0
            for t in trainees:
                try:
                    g = t.user.profile.gender
                    if g == 'male': male += 1
                    elif g == 'female': female += 1
                except UserProfile.DoesNotExist:
                    pass
            total = male + female
            f_pct = round(female / total * 100, 1) if total else 0
            grand_male += male
            grand_female += female
            rows.append([c.code, c.name_bn, total, male, female, f'{f_pct}%'])
        gt = grand_male + grand_female
        rows.append(['TOTAL', '', gt, grand_male, grand_female, f'{round(grand_female/gt*100, 1) if gt else 0}%'])
        return {
            'title': 'Gender Diversity Report',
            'headers': ['Code', 'Center', 'Total', 'Men', 'Women', 'Female %'],
            'rows': rows,
        }

    # ── Report 16: Regional (27 Centers) ─────────────────────────────────

    def regional(self):
        centers = Center.objects.filter(status='active').order_by('code')
        rows = []
        for c in centers:
            batches = Batch.objects.filter(center=c)
            if self.batch_ids:
                batches = batches.filter(id__in=self.batch_ids)
            trainees = Trainee.objects.filter(center=c)
            t_count = trainees.count()
            b_count = batches.count()
            placements = JobPlacement.objects.filter(batch__center=c).count()
            att_count = Attendance.objects.filter(batch__in=batches)
            total_sessions = att_count.count()
            attended = att_count.filter(status__in=('present', 'late')).count()
            att_rate = round(attended / total_sessions * 100, 1) if total_sessions else 0
            rows.append([c.code, c.name_bn, b_count, t_count, placements,
                         f'{att_rate}%', c.get_status_display()])
        return {
            'title': 'Regional Report (All Centers)',
            'headers': ['Code', 'Center', 'Batches', 'Trainees', 'Placements', 'Attendance', 'Status'],
            'rows': rows,
        }

    # ── Report 17: Monthly Trend ─────────────────────────────────────────

    def monthly_trend(self):
        months = int(self.params.get('months', 12))
        since = date.today() - timedelta(days=months * 30)

        trainees_qs = Trainee.objects.filter(created_at__gte=since)
        if self.center_ids:
            trainees_qs = trainees_qs.filter(center_id__in=self.center_ids)
        monthly_trainees = trainees_qs.annotate(
            month=TruncMonth('created_at'),
        ).values('month').annotate(count=Count('id')).order_by('month')

        apps_qs = Application.objects.filter(applied_at__gte=since)
        monthly_apps = apps_qs.annotate(
            month=TruncMonth('applied_at'),
        ).values('month').annotate(count=Count('id')).order_by('month')

        months_set = set()
        trainee_map = {str(r['month'])[:7]: r['count'] for r in monthly_trainees}
        app_map = {str(r['month'])[:7]: r['count'] for r in monthly_apps}
        for k in list(trainee_map.keys()) + list(app_map.keys()):
            months_set.add(k)
        rows = []
        for m in sorted(months_set):
            rows.append([m, trainee_map.get(m, 0), app_map.get(m, 0)])
        return {
            'title': 'Monthly Trend Report',
            'headers': ['Month', 'New Trainees', 'Applications'],
            'rows': rows,
        }

    # ── Report 18: Audit Log ─────────────────────────────────────────────

    def audit_log(self):
        q = Q()
        if self.date_from:
            q &= Q(created_at__date__gte=self.date_from)
        if self.date_to:
            q &= Q(created_at__date__lte=self.date_to)
        logs = ActionLog.objects.filter(q).select_related('user').order_by('-created_at')[:500]
        rows = []
        for log in logs:
            rows.append([
                log.created_at.strftime('%Y-%m-%d %H:%M'),
                log.user.full_name_bn if log.user else '-',
                log.action, log.target_type or '-',
                log.target_id or '-',
                log.description[:100] if log.description else '-',
                log.ip_address or '-',
            ])
        return {
            'title': 'System Activity (Audit Log)',
            'headers': ['Timestamp', 'User', 'Action', 'Target', 'Target ID', 'Description', 'IP'],
            'rows': rows,
        }

    # ── Report 19: TOR Compliance ────────────────────────────────────────

    def compliance(self):
        total_centers = Center.objects.filter(status='active').count()
        active_courses = Course.objects.filter(status='active').count()
        approved_trainers = Trainer.objects.filter(approval_status='approved').count()
        approved_assessors = Assessor.objects.filter(approval_status='approved').count()
        running_batches = Batch.objects.filter(status='running').count()
        completed_batches = Batch.objects.filter(status='completed').count()

        all_centers = Center.objects.filter(status='active')
        non_compliant = 0
        for c in all_centers:
            batches = Batch.objects.filter(center=c)
            att = Attendance.objects.filter(batch__in=batches)
            total_s = att.count()
            attnd = att.filter(status__in=('present', 'late')).count()
            rate = round(attnd / total_s * 100, 1) if total_s else 100
            if rate < 80:
                non_compliant += 1

        budget_total = Budget.objects.aggregate(s=Sum('allocated_amount'))['s'] or 0
        expended_total = Budget.objects.aggregate(s=Sum('expended_amount'))['s'] or 0

        rows = [
            ['Active Centers', str(total_centers), '✓' if total_centers == 27 else '⚠'],
            ['Active Courses', str(active_courses), '✓' if active_courses > 0 else '⚠'],
            ['Approved Trainers', str(approved_trainers), '✓' if approved_trainers > 0 else '⚠'],
            ['Approved Assessors', str(approved_assessors), '✓' if approved_assessors > 0 else '⚠'],
            ['Running Batches', str(running_batches), ''],
            ['Completed Batches', str(completed_batches), ''],
            ['Centers Below 80% Attendance', str(non_compliant), '⚠' if non_compliant > 0 else '✓'],
            ['Budget Utilization', f'{round(expended_total/budget_total*100, 1) if budget_total else 0}%', ''],
        ]
        return {
            'title': 'TOR Compliance Report',
            'headers': ['Requirement', 'Status', 'Compliance'],
            'rows': rows,
        }

    # ── Export dispatcher ────────────────────────────────────────────────

    def export(self, report_type, export_format='csv'):
        data = getattr(self, report_type)()
        headers = data['headers']
        rows = [[str(c) for c in r] for r in data['rows']]
        title = data['title']
        subtitle = f'Generated: {date.today().isoformat()}'

        exporter = ReportExporter()
        if export_format == 'excel':
            content = exporter.to_excel(headers, rows)
            ext = 'xlsx'
            mime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        elif export_format == 'pdf':
            content = exporter.to_pdf(title, headers, rows, subtitle)
            ext = 'pdf'
            mime = 'application/pdf'
        else:
            content = exporter.to_csv(headers, rows)
            ext = 'csv'
            mime = 'text/csv'
        return content, ext, mime, data['title']
