# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor_no', models.CharField(max_length=30, unique=True, verbose_name='মূল্যায়নকারী নং')),
                ('nid', models.CharField(max_length=17, unique=True, verbose_name='জাতীয় পরিচয়পত্র নং')),
                ('birth_certificate_no', models.CharField(blank=True, max_length=17, null=True, verbose_name='জন্ম নিবন্ধন নং')),
                ('date_of_birth', models.DateField(verbose_name='জন্ম তারিখ')),
                ('father_name_bn', models.CharField(max_length=255, verbose_name='পিতার নাম (বাংলায়)')),
                ('mother_name_bn', models.CharField(max_length=255, verbose_name='মাতার নাম (বাংলায়)')),
                ('education_qualification', models.TextField(verbose_name='শিক্ষাগত যোগ্যতা')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='অভিজ্ঞতা (বছর)')),
                ('expertise_area', models.CharField(max_length=255, verbose_name='দক্ষতার ক্ষেত্র')),
                ('certification', models.TextField(blank=True, verbose_name='সার্টিফিকেশন')),
                ('bank_account_no', models.CharField(blank=True, max_length=30, verbose_name='ব্যাংক একাউন্ট নং')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='ব্যাংকের নাম')),
                ('status', models.CharField(choices=[('pending', 'বিচারাধীন'), ('active', 'সক্রিয়'), ('suspended', 'স্থগিত')], default='pending', max_length=15, verbose_name='অবস্থা')),
                ('approval_status', models.CharField(choices=[('pending', 'অনুমোদিত হয়নি'), ('approved', 'অনুমোদিত'), ('rejected', 'বাতিল')], default='pending', max_length=15, verbose_name='অনুমোদনের অবস্থা')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessors', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_profile', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'মূল্যায়নকারী',
                'verbose_name_plural': 'মূল্যায়নকারীগণ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainerAssessorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_at', models.DateTimeField(auto_now_add=True, verbose_name='রূপান্তরের তারিখ')),
                ('remarks', models.TextField(blank=True, verbose_name='মন্তব্য')),
                ('assessor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_link', to='assessors.assessor', verbose_name='মূল্যায়নকারী')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='রূপান্তরকারী')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_links', to='trainers.trainer', verbose_name='প্রশিক্ষক')),
            ],
            options={
                'verbose_name': 'প্রশিক্ষক-মূল্যায়নকারী লিংক',
                'verbose_name_plural': 'প্রশিক্ষক-মূল্যায়নকারী লিংক',
            },
        ),
        migrations.CreateModel(
            name='AssessorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='প্রাথমিক')),
                ('status', models.CharField(choices=[('pending', 'বিচারাধীন'), ('active', 'সক্রিয়'), ('suspended', 'স্থগিত')], default='pending', max_length=15, verbose_name='অবস্থা')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessor_mappings', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='assessors.assessor', verbose_name='মূল্যায়নকারী')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_mappings', to='centers.center', verbose_name='কেন্দ্র')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_mappings', to='courses.course', verbose_name='কোর্স')),
            ],
            options={
                'verbose_name': 'মূল্যায়নকারী ম্যাপিং',
                'verbose_name_plural': 'মূল্যায়নকারী ম্যাপিং',
                'ordering': ('assessor', 'center'),
                'unique_together': {('assessor', 'center', 'course')},
            },
        ),
    ]
