# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='প্রতিবেদনের শিরোনাম')),
                ('report_type', models.CharField(choices=[('attendance', 'উপস্থিতি প্রতিবেদন'), ('assessment', 'মূল্যায়ন প্রতিবেদন'), ('certificate', 'সার্টিফিকেট প্রতিবেদন'), ('placement', 'চাকরি প্রতিবেদন'), ('center_wise', 'কেন্দ্রভিত্তিক প্রতিবেদন'), ('course_wise', 'কোর্সভিত্তিক প্রতিবেদন'), ('summary', 'সারসংক্ষেপ')], max_length=30, verbose_name='প্রতিবেদনের ধরণ')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='প্যারামিটার')),
                ('file', models.FileField(blank=True, upload_to='reports/', verbose_name='ফাইল')),
                ('is_ready', models.BooleanField(default=False, verbose_name='প্রস্তুত')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='টাস্ক আইডি')),
                ('error_message', models.TextField(blank=True, verbose_name='ত্রুটির বিবরণ')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='প্রস্তুতের তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='প্রস্তুতকারী')),
            ],
            options={
                'verbose_name': 'প্রতিবেদন',
                'verbose_name_plural': 'প্রতিবেদনসমূহ',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['report_type', 'is_ready'], name='reports_rep_report__f10c64_idx')],
            },
        ),
    ]
