# Generated by Django 4.2.16 on 2026-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('attendance', 'উপস্থিতি প্রতিবেদন'), ('assessment', 'মূল্যায়ন প্রতিবেদন'), ('certificate', 'সার্টিফিকেট প্রতিবেদন'), ('placement', 'চাকরি প্রতিবেদন'), ('placement_tracking', 'চাকরি ট্র্যাকিং প্রতিবেদন'), ('financial', 'আর্থিক প্রতিবেদন'), ('center_wise', 'কেন্দ্রভিত্তিক প্রতিবেদন'), ('course_wise', 'কোর্সভিত্তিক প্রতিবেদন'), ('summary', 'সারসংক্ষেপ')], max_length=30, verbose_name='প্রতিবেদনের ধরণ'),
        ),
    ]
