# Generated by Django 4.2.16 on 2026-05-08 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0002_actionlog'),
        ('reports', '0002_alter_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='প্রতিবেদনের ধরণ')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম')),
                ('frequency', models.CharField(choices=[('daily', 'প্রতিদিন'), ('weekly', 'সাপ্তাহিক'), ('monthly', 'মাসিক')], default='weekly', max_length=10, verbose_name='ফ্রিকোয়েন্সি')),
                ('recipients', models.TextField(help_text='কমা দিয়ে আলাদা করুন', verbose_name='ইমেইল প্রাপক')),
                ('export_format', models.CharField(default='pdf', max_length=10, verbose_name='এক্সপোর্ট ফরম্যাট')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='প্যারামিটার')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='শেষ চালানোর তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centers', models.ManyToManyField(blank=True, to='centers.center', verbose_name='কেন্দ্র')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
            ],
            options={
                'verbose_name': 'নির্ধারিত প্রতিবেদন',
                'verbose_name_plural': 'নির্ধারিত প্রতিবেদনসমূহ',
                'ordering': ('-created_at',),
            },
        ),
    ]
