# Generated by Django 4.2.16 on 2026-05-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='যেমন: DHAKA_TCU, CHITT_TCU', max_length=20, unique=True, verbose_name='কেন্দ্র কোড')),
                ('name_bn', models.CharField(max_length=255, verbose_name='কেন্দ্রের নাম (বাংলায়)')),
                ('name_en', models.CharField(max_length=255, verbose_name='কেন্দ্রের নাম (ইংরেজিতে)')),
                ('short_name_bn', models.CharField(blank=True, max_length=50, verbose_name='সংক্ষিপ্ত নাম (বাংলায়)')),
                ('logo_url', models.URLField(blank=True, verbose_name='লোগো URL')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('phone', models.CharField(max_length=15, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('website_url', models.URLField(blank=True, verbose_name='ওয়েবসাইট')),
                ('contact_person_name', models.CharField(blank=True, max_length=255, verbose_name='যোগাযোগ ব্যক্তির নাম')),
                ('contact_person_phone', models.CharField(blank=True, max_length=15, verbose_name='যোগাযোগ ব্যক্তির মোবাইল')),
                ('status', models.CharField(choices=[('active', 'সক্রিয়'), ('suspended', 'স্থগিত')], default='active', max_length=10, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'প্রশিক্ষণ কেন্দ্র',
                'verbose_name_plural': 'প্রশিক্ষণ কেন্দ্রসমূহ',
                'ordering': ('name_en',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=30, unique=True, verbose_name='কর্মচারী নং')),
                ('designation_bn', models.CharField(max_length=255, verbose_name='পদবী (বাংলায়)')),
                ('designation_en', models.CharField(max_length=255, verbose_name='পদবী (ইংরেজিতে)')),
                ('joining_date', models.DateField(verbose_name='যোগদানের তারিখ')),
                ('is_contact_person', models.BooleanField(default=False, verbose_name='যোগাযোগ ব্যক্তি')),
                ('status', models.CharField(choices=[('active', 'সক্রিয়'), ('inactive', 'নিষ্ক্রিয়'), ('transferred', 'বদলি')], default='active', max_length=15, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='centers.center', verbose_name='প্রশিক্ষণ কেন্দ্র')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center_employee', to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'কর্মচারী',
                'verbose_name_plural': 'কর্মচারীগণ',
                'ordering': ('center', 'employee_no'),
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50, verbose_name='কক্ষ নম্বর')),
                ('location_bn', models.CharField(max_length=255, verbose_name='অবস্থান (বাংলায়)')),
                ('location_en', models.CharField(max_length=255, verbose_name='অবস্থান (ইংরেজিতে)')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='ধারণক্ষমতা')),
                ('equipment', models.TextField(blank=True, verbose_name='সরঞ্জাম')),
                ('status', models.CharField(choices=[('available', 'উপলব্ধ'), ('unavailable', 'অনুপলব্ধ'), ('maintenance', 'রক্ষণাবেক্ষণাধীন')], default='available', max_length=15, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='centers.center', verbose_name='প্রশিক্ষণ কেন্দ্র')),
            ],
            options={
                'verbose_name': 'অবকাঠামো',
                'verbose_name_plural': 'অবকাঠামো',
                'ordering': ('center', 'room_no'),
                'unique_together': {('center', 'room_no')},
            },
        ),
    ]
