# Generated by Django 4.2.16 on 2026-05-08 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='কর্ম')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='লক্ষ্যের ধরন')),
                ('target_id', models.CharField(blank=True, max_length=20, verbose_name='লক্ষ্যের আইডি')),
                ('description', models.TextField(blank=True, verbose_name='বিবরণ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'কার্যক্রম লগ',
                'verbose_name_plural': 'কার্যক্রম লগ',
                'ordering': ('-created_at',),
            },
        ),
    ]
