# Generated by Django 5.0 on 2026-06-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='code',
            field=models.CharField(blank=True, help_text='স্বয়ংক্রিয় জেনারেট হবে (যেমন: 0001, 0002)', max_length=20, unique=True, verbose_name='কেন্দ্র কোড'),
        ),
    ]
