# Generated by Django 5.0 on 2026-06-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='active_batches',
            field=models.PositiveIntegerField(default=0, verbose_name='সক্রিয় ব্যাচ'),
        ),
        migrations.AddField(
            model_name='center',
            name='attendance_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='উপস্থিতির হার (%)'),
        ),
        migrations.AddField(
            model_name='center',
            name='completed_batches',
            field=models.PositiveIntegerField(default=0, verbose_name='সমাপ্ত ব্যাচ'),
        ),
        migrations.AddField(
            model_name='center',
            name='completed_trainees',
            field=models.PositiveIntegerField(default=0, verbose_name='সফল সমাপ্তি'),
        ),
        migrations.AddField(
            model_name='center',
            name='dropped_trainees',
            field=models.PositiveIntegerField(default=0, verbose_name='ঝরে পড়া'),
        ),
        migrations.AddField(
            model_name='center',
            name='enrolled_trainees',
            field=models.PositiveIntegerField(default=0, verbose_name='নথিভুক্ত'),
        ),
        migrations.AddField(
            model_name='center',
            name='placement_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='চাকরি স্থাপনের হার (%)'),
        ),
        migrations.AddField(
            model_name='center',
            name='running_batches',
            field=models.PositiveIntegerField(default=0, verbose_name='চলমান ব্যাচ'),
        ),
        migrations.AddField(
            model_name='center',
            name='total_batches',
            field=models.PositiveIntegerField(default=0, verbose_name='মোট ব্যাচ'),
        ),
        migrations.AddField(
            model_name='center',
            name='total_trainees',
            field=models.PositiveIntegerField(default=0, verbose_name='মোট প্রশিক্ষণার্থী'),
        ),
    ]
