# Generated by Django 5.0 on 2026-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_center_active_batches_center_attendance_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_type',
            field=models.CharField(choices=[('metro', 'মহানগর'), ('urban', 'শহর'), ('semi_urban', 'আধা-শহর'), ('rural', 'গ্রামীণ'), ('remote', 'দুর্গম')], default='urban', max_length=20, verbose_name='কেন্দ্রের ধরন'),
        ),
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='অক্ষাংশ'),
        ),
        migrations.AddField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='দ্রাঘিমাংশ'),
        ),
        migrations.AddField(
            model_name='center',
            name='overflow_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='প্রতি কেন্দ্রের জন্য বেস সিটের অতিরিক্ত আবেদনের শতকরা হার', max_digits=5, verbose_name='অতিরিক্ত আবেদনের হার (%)'),
        ),
        migrations.AddField(
            model_name='center',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='কেন্দ্রের গুণগত মান স্কোর, রুটিং প্রাধান্যে ব্যবহৃত', max_digits=5, verbose_name='মান স্কোর (0-100)'),
        ),
    ]
