# Generated by Django 5.0 on 2026-06-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_center_center_type_center_latitude_center_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='কর্ম'),
        ),
    ]
