# Generated by Django 6.0.6 on 2026-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_alter_actionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='seats_per_trainer',
            field=models.PositiveIntegerField(default=25, help_text='একজন প্রশিক্ষকের জন্য কতজন প্রশিক্ষণার্থী বরাদ্দ করা যাবে', verbose_name='প্রতি প্রশিক্ষকে আসন সংখ্যা'),
        ),
    ]
