# Generated by Django 4.2.16 on 2026-05-07 19:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bn', models.CharField(max_length=255, verbose_name='শিরোনাম (বাংলায়)')),
                ('title_en', models.CharField(max_length=255, verbose_name='শিরোনাম (ইংরেজিতে)')),
                ('description', ckeditor.fields.RichTextField(verbose_name='বিস্তারিত')),
                ('application_start_date', models.DateField(verbose_name='আবেদন শুরুর তারিখ')),
                ('application_end_date', models.DateField(verbose_name='আবেদনের শেষ তারিখ')),
                ('training_start_date', models.DateField(verbose_name='প্রশিক্ষণ শুরুর তারিখ')),
                ('training_end_date', models.DateField(verbose_name='প্রশিক্ষণ শেষের তারিখ')),
                ('total_seats', models.PositiveIntegerField(verbose_name='মোট আসন')),
                ('remaining_seats', models.PositiveIntegerField(verbose_name='অবশিষ্ট আসন')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, help_text='খালি রাখলে কোর্সের ডিফল্ট ফি নেওয়া হবে', max_digits=10, null=True, verbose_name='কোর্স ফি (ঐচ্ছিক)')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('published', 'প্রকাশিত'), ('closed', 'বন্ধ'), ('completed', 'সমাপ্ত')], default='draft', max_length=15, verbose_name='অবস্থা')),
                ('public_url', models.SlugField(blank=True, help_text='সাধারণ ব্যবহারকারীদের জন্য ইউনিক লিংক', max_length=100, null=True, unique=True, verbose_name='পাবলিক ইউআরএল')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='প্রকাশের তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulars', to='centers.center', verbose_name='প্রশিক্ষণ কেন্দ্র')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulars', to='courses.course', verbose_name='কোর্স')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_circulars', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
            ],
            options={
                'verbose_name': 'সার্কুলার',
                'verbose_name_plural': 'সার্কুলারসমূহ',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'public_url'], name='circulars_c_status_72dfbf_idx'), models.Index(fields=['center', 'status'], name='circulars_c_center__30ce04_idx')],
            },
        ),
    ]
