# Generated by Django 5.0 on 2026-06-07 00:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_center_to_eligible_centers(apps, schema_editor):
    Circular = apps.get_model('circulars', 'Circular')
    for circular in Circular.objects.all():
        if circular.center_id:
            circular.eligible_centers.add(circular.center_id)


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_actionlog'),
        ('circulars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_type', models.CharField(choices=[('age', 'বয়স'), ('education', 'শিক্ষাগত যোগ্যতা'), ('experience_years', 'অভিজ্ঞতা (বছর)'), ('height_cm', 'উচ্চতা (সেমি)'), ('weight_kg', 'ওজন (কেজি)'), ('boolean', 'হ্যাঁ/না'), ('text_match', 'টেক্সট ম্যাচ'), ('number', 'সংখ্যা')], max_length=20, verbose_name='নির্ধারক')),
                ('label_bn', models.CharField(max_length=255, verbose_name='লেবেল (বাংলায়)')),
                ('label_en', models.CharField(blank=True, max_length=255, verbose_name='লেবেল (ইংরেজিতে)')),
                ('operator', models.CharField(choices=[('>=', '>= (এর সমান বা বেশি)'), ('<=', '<= (এর সমান বা কম)'), ('==', '== (সমান)'), ('>', '> (এর বেশি)'), ('<', '< (এর কম)'), ('between', 'এর মধ্যে')], max_length=10, verbose_name='তুলনামূলক অপারেটর')),
                ('expected_value', models.CharField(help_text='যেমন: 18 (বয়সের জন্য), ssc (শিক্ষার জন্য), 18,35 (between এর জন্য)', max_length=255, verbose_name='প্রত্যাশিত মান')),
                ('score', models.DecimalField(decimal_places=2, help_text='এই শর্ত পূরণ করলে প্রাপ্ত স্কোর', max_digits=10, verbose_name='স্কোর')),
                ('required', models.BooleanField(default=True, verbose_name='বাধ্যতামূলক')),
                ('order', models.IntegerField(default=0, verbose_name='ক্রম')),
            ],
            options={
                'verbose_name': 'চেকলিস্ট আইটেম',
                'verbose_name_plural': 'চেকলিস্ট আইটেমসমূহ',
                'ordering': ('order',),
            },
        ),
        migrations.RemoveIndex(
            model_name='circular',
            name='circulars_c_center__30ce04_idx',
        ),
        migrations.AddField(
            model_name='circular',
            name='auto_screen_min_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='অটো-স্ক্রিন পাস করার জন্য প্রয়োজনীয় ন্যূনতম স্কোর', max_digits=10, verbose_name='অটো-স্ক্রিন ন্যূনতম স্কোর'),
        ),
        migrations.AddField(
            model_name='circular',
            name='auto_screen_total_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='চেকলিস্টের সর্বোচ্চ সম্ভাব্য স্কোর', max_digits=10, verbose_name='অটো-স্ক্রিন মোট স্কোর'),
        ),
        migrations.AddField(
            model_name='circular',
            name='eligible_centers',
            field=models.ManyToManyField(help_text='যে সমস্ত কেন্দ্রের জন্য এই সার্কুলার প্রযোজ্য', related_name='circulars', to='centers.center', verbose_name='উপযুক্ত কেন্দ্রসমূহ'),
        ),
        migrations.RunPython(migrate_center_to_eligible_centers, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='circular',
            name='center',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='circular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='circulars.circular', verbose_name='সার্কুলার'),
        ),
    ]
