# Generated by Django 5.0 on 2026-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_actionlog'),
        ('circulars', '0002_checklistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='all_centers',
            field=models.BooleanField(default=False, help_text='সকল কেন্দ্রের জন্য প্রযোজ্য (চিহ্নিত করলে উপযুক্ত কেন্দ্র নির্বাচনের প্রয়োজন নেই)', verbose_name='সব কেন্দ্র'),
        ),
        migrations.AlterField(
            model_name='circular',
            name='eligible_centers',
            field=models.ManyToManyField(blank=True, help_text='যে সমস্ত কেন্দ্রের জন্য এই সার্কুলার প্রযোজ্য', related_name='circulars', to='centers.center', verbose_name='উপযুক্ত কেন্দ্রসমূহ'),
        ),
    ]
