# Generated by Django 5.0 on 2026-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0003_circular_all_centers_alter_circular_eligible_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='circular_no',
            field=models.CharField(blank=True, help_text='যেমন: BRTC/সার্কুলার/২০২৬/০১', max_length=50, null=True, verbose_name='সার্কুলার নম্বর'),
        ),
        migrations.AddField(
            model_name='circular',
            name='edition',
            field=models.PositiveIntegerField(default=1, help_text='সার্কুলারের সংস্করণ নম্বর', verbose_name='সংস্করণ'),
        ),
    ]
