# Generated by Django 5.0 on 2026-06-12 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulars', '0004_circular_no_edition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='default_overflow_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='সার্কুলার লেভেলে ডিফল্ট P মান। প্রতি কেন্দ্রের নিজস্ব P না থাকলে এই মান ব্যবহার হবে।', max_digits=5, verbose_name='ডিফল্ট অতিরিক্ত আবেদনের হার (%)'),
        ),
        migrations.AddField(
            model_name='circular',
            name='routing_weight_distance',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='w₂ — দূরত্বের উপর ভিত্তি করে রুটিং স্কোরের ওজন', max_digits=3, verbose_name='রুটিং ওজন (দূরত্ব)'),
        ),
        migrations.AddField(
            model_name='circular',
            name='routing_weight_merit',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='w₃ — কেন্দ্রের গুণগত মানের উপর ভিত্তি করে রুটিং স্কোরের ওজন', max_digits=3, verbose_name='রুটিং ওজন (মেধা)'),
        ),
        migrations.AddField(
            model_name='circular',
            name='routing_weight_seats',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='w₁ — উপলব্ধ আসনের উপর ভিত্তি করে রুটিং স্কোরের ওজন', max_digits=3, verbose_name='রুটিং ওজন (আসন)'),
        ),
        migrations.AddField(
            model_name='circular',
            name='waitlist_validity_days',
            field=models.PositiveIntegerField(default=30, help_text='ব্যাচ শুরুর পর কত দিন পর্যন্ত অপেক্ষমাণ তালিকা বৈধ থাকবে', verbose_name='অপেক্ষমাণ তালিকার বৈধতা (দিন)'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='কমিটির নাম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='circulars.circular', verbose_name='সার্কুলার')),
                ('members', models.ManyToManyField(related_name='selection_committees', to=settings.AUTH_USER_MODEL, verbose_name='কমিটির সদস্য')),
            ],
            options={
                'verbose_name': 'নির্বাচন কমিটি',
                'verbose_name_plural': 'নির্বাচন কমিটিসমূহ',
            },
        ),
    ]
