# Generated by Django 5.0 on 2026-06-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_center_center_type_center_latitude_center_longitude_and_more'),
        ('circulars', '0005_circular_default_overflow_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularCenterAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_seats', models.PositiveIntegerField(verbose_name='বরাদ্দকৃত আসন')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circular_allocations', to='centers.center', verbose_name='কেন্দ্র')),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_allocations', to='circulars.circular', verbose_name='সার্কুলার')),
            ],
            options={
                'verbose_name': 'সার্কুলার কেন্দ্র বরাদ্দ',
                'verbose_name_plural': 'সার্কুলার কেন্দ্র বরাদ্দ',
                'unique_together': {('circular', 'center')},
            },
        ),
    ]
